### ISSUE TITLE
iter() returned non-iterator of type 'xmlCoreDepthFirstItertor'

### ISSUE THREAD

**Issue by xradiation** [virt-manager/virt-manager#120]
hi guys, 
    am basically facing this error every single action i do it seems to be related to `python itertools` but am not completely sure, Here is the error message when i tried to delete a host usb device from one vm, just as a side note I've even tried to edit the xml description but that didn't work either so here goes: 

just for completeness sake : 
OS : Archlinux
Virt-manager : 2.2.1
Libvirt : libvirtd (libvirt) 6.5.0 ( aur package ----> libvirt-git 6.4.0.r84.g63d08bec0b-1 )

`Error Removing Device: iter() returned non-iterator of type 'xmlCoreDepthFirstItertor'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/details/details.py", line 1935, in remove_device
    self.vm.remove_device(devobj)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 429, in remove_device
    xmlobj.remove_device(editdev)
  File "/usr/share/virt-manager/virtinst/guest.py", line 505, in remove_device
    self.devices.remove_child(dev)
  File "/usr/share/virt-manager/virtinst/xmlbuilder.py", line 723, in remove_child
    self._xmlstate.xmlapi.node_force_remove(xpath)
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 183, in node_force_remove
    self._node_remove_child(parentnode, childnode)
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 390, in _node_remove_child
    if all([node_is_text(n) for n in parentnode.children]):
TypeError: iter() returned non-iterator of type 'xmlCoreDepthFirstItertor'`

**Comment by xradiation** [comment]
for every one who's facing the same or similar issue, in my case doing the following steps solved it :
- installing some "optional" libvirt dependecies : 
`dmidecode`
`libvirt-storage-gluster`
`libvirt-storage-iscsi-direct`
`libvirt-storage-rbd`
`radvd`

- make sure that these packages are up to date : 
`libxml2`
`libxml2-python3`
`libvirt` (I've switched back to the official repos package)
and of course `virt-manager` (official repos package)
