### ISSUE TITLE
Error in when trying to customize vm

### ISSUE THREAD

**Issue by Solumnant** [virt-manager/virt-manager#124]
I'm trying to customize a vm using virt-manager on ubuntu but I'm hitting the following error:

`Error starting installation: Namespace GtkVnc not available

Traceback (most recent call last):
File "/usr/share/virt-manager/virtManager/createvm.py", line 1923, in _finish_clicked
self._show_customize_dialog(guest, installer)
File "/usr/share/virt-manager/virtManager/createvm.py", line 1956, in _show_customize_dialog
self._customize_window = vmmVMWindow(orig_vdomain, self.topwin)
File "/usr/share/virt-manager/virtManager/vmwindow.py", line 72, in init
from .details.console import vmmConsolePages
File "/usr/share/virt-manager/virtManager/details/console.py", line 15, in
from .viewers import SpiceViewer, VNCViewer, have_spice_gtk
File "/usr/share/virt-manager/virtManager/details/viewers.py", line 14, in
gi.require_version('GtkVnc', '2.0')
File "/usr/lib/python3/dist-packages/gi/init.py", line 130, in require_version
raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkVnc not available`

Trying to update says it's not installed and trying to install virt-manager yields the following error: 

sudo apt-get install virt-manager 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 virt-manager : Depends: python-libvirt (>= 0.7.1) but it is not going to be installed
                Depends: virtinst (>= 1:1.5.1-0ubuntu1.2) but it is not going to be installed
                Recommends: libvirt-daemon-system (>= 1.2.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

and trying to install python-libvirt yields

sudo apt-get install python-libvirt 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-libvirt : Depends: libvirt0 (>= 3.4.0) but it is not installable
                  Recommends: libvirt-daemon but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

trying to install libvirt0 yields:

 sudo apt-get install libvirt0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libvirt0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libvirt0:i386

E: Package 'libvirt0' has no installation candidate

and installing libvirt0:i386 doesn't allow for python-libvirt to be installed.

I do have Virtual Machine Manager available to me through Ubuntu, so I'm not sure why it says virt-manager isn't installed.

**Comment by Solumnant** [comment]
The libvirtd wasn't running
