### ISSUE TITLE
Error changing VM configuration: iter() returned non-iterator of type 'xmlCoreDepthFirstItertor'

### ISSUE THREAD

**Issue by PowerMan2206** [virt-manager/virt-manager#132]
Whenever I try to change a VM's config, I get this error:
```
Error changing VM configuration: iter() returned non-iterator of type 'xmlCoreDepthFirstItertor'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/addhardware.py", line 367, in change_config_helper
    define_func(**define_args)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 540, in define_boot
    guest.set_boot_order(boot_order, legacy=legacy)
  File "/usr/share/virt-manager/virtinst/guest.py", line 421, in set_boot_order
    self._set_device_boot_order(boot_order)
  File "/usr/share/virt-manager/virtinst/guest.py", line 405, in _set_device_boot_order
    self.os.bootorder = []
  File "/usr/share/virt-manager/virtinst/domain/os.py", line 76, in _set_bootorder
    self.remove_child(dev)
  File "/usr/share/virt-manager/virtinst/xmlbuilder.py", line 723, in remove_child
    self._xmlstate.xmlapi.node_force_remove(xpath)
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 183, in node_force_remove
    self._node_remove_child(parentnode, childnode)
  File "/usr/share/virt-manager/virtinst/xmlapi.py", line 390, in _node_remove_child
    if all([node_is_text(n) for n in parentnode.children]):
TypeError: iter() returned non-iterator of type 'xmlCoreDepthFirstItertor'
```
I installed `libxml2-python3` with `pip` and it's on version 2.9.5,  latest according to `pip`, `virt-manager` and it's dependencies were installed with `pacman`. I found other reports of this bug, but none of their fixes worked. #108 suggested to update `libxml2-python3` to 2.9.10, but `pip` won't let me do it.
I'm using Arch Linux.

**Comment by phrdina** [comment]
First of all, I honestly don't understand why people install packages from pip if they have the same or newer version available from packages provided by distribution.

#108 suggested to update libxml2-python3 but that suggestion was incorrect if you would read additional comments. In that issue I mentioned that on Arch Linux the python bindings are part of the libxml2 package as you can see here https://www.archlinux.org/packages/extra/x86_64/libxml2/files/.

You should uninstall the libxml2-python3 which should solve the issue.
