### ISSUE TITLE
cannot touch existing FreeBSD vm in qemu:///system by virt-manager ui

### ISSUE THREAD

**Issue by holishing** [virt-manager/virt-manager#168]
**Distro**: ArchLinux

`libvirt` version: 6.8.0

confirmed `virt-manager` version: git master == 3.1.0

**Description**:

When I try to find my FreeBSD VM in virt-manager, it was disappeared,
the log below is debug mode message:

```
[Sat, 17 Oct 2020 13:47:37 virt-manager 2713047] DEBUG (libvirtobject:179) Error initializing libvirt state for <vmmDomain name=freebsd12.1 id=0x7fc436e87d80>
Traceback (most recent call last):
  File "./virtManager/object/libvirtobject.py", line 177, in init_libvirt_state
    self._init_libvirt_state()
  File "./virtManager/object/domain.py", line 390, in _init_libvirt_state
    self.snapshots_supported()
  File "./virtManager/object/domain.py", line 460, in snapshots_supported
    if self.list_snapshots():
  File "./virtManager/object/domain.py", line 1101, in list_snapshots
    for rawsnap in self._backend.listAllSnapshots():
  File "/usr/lib/python3.8/site-packages/libvirt.py", line 3238, in listAllSnapshots
    return [virDomainSnapshot(self, _obj=snapptr) for snapptr in ret]
  File "/usr/lib/python3.8/site-packages/libvirt.py", line 3238, in <listcomp>
    return [virDomainSnapshot(self, _obj=snapptr) for snapptr in ret]
  File "/usr/lib/python3.8/site-packages/libvirt.py", line 7003, in __init__
    self._dom = dom
NameError: name 'dom' is not defined
Exception ignored in: <function virDomainSnapshot.__del__ at 0x7fc43e8448b0>
Traceback (most recent call last):
```

and I still can operate my freebsd vm in virsh, for e.g. `virsh -c qemu:///system list --all`:

```
$ virsh -c qemu:///system list 
 Id   Name          State
-----------------------------
 1    freebsd12.1   running
```

Please help to confirm the problem, thanks!

**Comment by crobinso** [comment]
Thanks for the report. libvirt-python 6.8.0 has a regression that is causing this. Please ask your distro to include this patch, or wait until the next libvirt-python release: https://gitlab.com/libvirt/libvirt-python/-/commit/613411502d2cdf3541837710239409044a376b0a
