### ISSUE TITLE
virt-clone can't handle domains with rbd volumes

### ISSUE THREAD

**Issue by jamincollins** [virt-manager/virt-manager#177]
**Distro**: Arch Linux

Continuation from: https://bugzilla.redhat.com/show_bug.cgi?id=1413824

```
$ git log --oneline -n1
04ad8df7 (HEAD -> master, origin/master, origin/HEAD) Added Debian's armv7l UEFI binary. Closes #174
$ DOMAIN=ubuntu
$ ./virt-clone --debug --connect qemu:///system --print-xml --original ${DOMAIN} --name ${DOMAIN}-new --auto-clone
[Tue, 03 Nov 2020 14:13:38 virt-clone 2083711] DEBUG (cli:204) Launched with command line: ./virt-clone --debug --connect qemu:///system --print-xml --original ubuntu --name ubuntu-new --auto-clone
[Tue, 03 Nov 2020 14:13:38 virt-clone 2083711] DEBUG (cli:216) Requesting libvirt URI qemu:///system
[Tue, 03 Nov 2020 14:13:38 virt-clone 2083711] DEBUG (cli:219) Received libvirt URI qemu:///system
[Tue, 03 Nov 2020 14:13:38 virt-clone 2083711] DEBUG (cloner:320) Original XML:
<domain type='kvm'>
  <name>ubuntu</name>
  <uuid>bb401a18-16ae-44e9-824c-99dd06533215</uuid>
  <memory unit='KiB'>2097152</memory>
  <currentMemory unit='KiB'>2097152</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <os>
    <type arch='x86_64' machine='pc-1.3'>hvm</type>
    <bootmenu enable='yes'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <cpu mode='custom' match='exact' check='none'>
    <model fallback='forbid'>qemu64</model>
  </cpu>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='network' device='disk'>
      <driver name='qemu' type='raw' cache='none' io='native'/>
      <auth username='libvirt'>
        <secret type='ceph' uuid='910ca912-727c-4e80-abbd-6f1bdc33c181'/>
      </auth>
      <source protocol='rbd' name='vms/ubuntu'>
        <host name='skald-1' port='6789'/>
        <host name='langhus-1' port='6789'/>
        <host name='langhus-2' port='6789'/>
      </source>
      <target dev='vda' bus='virtio'/>
      <boot order='1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/var/lib/libvirt/images/ubuntu-18.04.1-desktop-amd64.iso'/>
      <target dev='hda' bus='ide'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='ide' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <controller type='usb' index='0' model='piix3-uhci'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'/>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </controller>
    <interface type='bridge'>
      <mac address='00:16:3e:54:a5:93'/>
      <source bridge='internal'/>
      <model type='virtio'/>
      <boot order='2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='vnc' port='-1' autoport='yes'>
      <listen type='address'/>
    </graphics>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </memballoon>
  </devices>
</domain>

[Tue, 03 Nov 2020 14:13:38 virt-clone 2083711] DEBUG (cloner:368) Auto-generated clone name 'ubuntu-clone'
[Tue, 03 Nov 2020 14:13:40 virt-clone 2083711] DEBUG (cloner:332) Wants cloning: size=0.0 path=rbd://skald-1:6789/vms/ubuntu
[Tue, 03 Nov 2020 14:13:40 virt-clone 2083711] DEBUG (cloner:530) Clone guest xml diff:
--- Original
+++ New
@@ -1,6 +1,6 @@
 <domain type="kvm">
-  <name>ubuntu</name>
-  <uuid>bb401a18-16ae-44e9-824c-99dd06533215</uuid>
+  <name>ubuntu-new</name>
+  <uuid>e6c81627-f4aa-4961-b673-bbeb90fba222</uuid>
   <memory unit="KiB">2097152</memory>
   <currentMemory unit="KiB">2097152</currentMemory>
   <vcpu placement="static">2</vcpu>
@@ -54,7 +54,7 @@
       <address type="pci" domain="0x0000" bus="0x00" slot="0x07" function="0x0"/>
     </controller>
     <interface type="bridge">
-      <mac address="00:16:3e:54:a5:93"/>
+      <mac address="52:54:00:2e:8e:32"/>
       <source bridge="internal"/>
       <model type="virtio"/>
       <boot order="2"/>

[Tue, 03 Nov 2020 14:13:40 virt-clone 2083711] DEBUG (cli:255)   File "./virt-clone", line 9, in <module>
    virtclone.runcli()
  File "./virtinst/virtclone.py", line 211, in runcli
    fail(main_e)
  File "./virtinst/cli.py", line 255, in fail
    log.debug("".join(traceback.format_stack()))

[Tue, 03 Nov 2020 14:13:40 virt-clone 2083711] ERROR (cli:256) Could not determine original disk information: Disk type 'network' is not cloneable.
[Tue, 03 Nov 2020 14:13:40 virt-clone 2083711] DEBUG (cli:258) 
Traceback (most recent call last):
  File "./virtinst/virtclone.py", line 205, in runcli
    sys.exit(main())
  File "./virtinst/virtclone.py", line 189, in main
    _validate_disks(cloner)
  File "./virtinst/virtclone.py", line 60, in _validate_disks
    diskinfo.raise_error()
  File "./virtinst/cloner.py", line 266, in raise_error
    raise ValueError(err)
ValueError: Could not determine original disk information: Disk type 'network' is not cloneable.
```

> In your setup, are you using libvirt storage pools for the rbd volume? 

Yes.

```
$ virsh pool-dumpxml vms
<pool type='rbd'>
  <name>vms</name>
  <uuid>61cfc0c0-f9f9-4927-9e3b-fd053711c690</uuid>
  <capacity unit='bytes'>47522550530048</capacity>
  <allocation unit='bytes'>18639936493945</allocation>
  <available unit='bytes'>15728292331520</available>
  <source>
    <host name='skald-1' port='6789'/>
    <host name='langhus-1' port='6789'/>
    <host name='langhus-2' port='6789'/>
    <name>vms</name>
    <auth type='ceph' username='libvirt'>
      <secret uuid='910ca912-727c-4e80-abbd-6f1bdc33c181'/>
    </auth>
  </source>
</pool>
```

Not entirely sure what you're asking for when you say:
> storage XML matching the storage volume that the VM XML mentioned above is using.

```
$ virsh vol-dumpxml vms/ubuntu
<volume type='network'>
  <name>ubuntu</name>
  <key>vms/ubuntu</key>
  <source>
  </source>
  <capacity unit='bytes'>21474836480</capacity>
  <allocation unit='bytes'>21474836480</allocation>
  <target>
    <path>vms/ubuntu</path>
    <format type='raw'/>
  </target>
</volume>
```

**Comment by crobinso** [comment]
Thanks for following up. Yup that's the info I wanted.

Right now the problem is that virt-install fails to look up source pool + vol combo from the VM <disk> XML, so we don't think the storage is managed, and therefore uncloneable. That should be fixable with your example XML but there may be other problems after that, we will see

**Comment by crobinso** [comment]
I spent a fair bit of time looking at this.

Unfortunately throughout virt-install shared code and virt-clone specific code, there's lots of assumptions sprinkled around that when dealing with disk storage we can do regular filesystem path manipulation, like dirname, basename, abs vs relative paths, looking up pools and volumes based on path fields, deriving parent pool identifying info from a volume's path in isolation, etc. These assumptions don't apply to rbd volume info though.

So the options to get this to work are either: hack a lot of rbd specific code paths into the cloner infrastructure, or do a much larger series of changes to common infrastructure that is then used with small changes for cloning. The latter is my preference but it will be a good chunk of work and I don't have the time for it now. So this is being put in the backlog.

**Comment by PenelopeFudd** [comment]
In the meantime, could an error message be added that says "rbd volumes are not supported by virt-clone yet, please see https://github.com/virt-manager/virt-manager/issues/177" when this comes up?  It's ok that the changes will take time, but it's maddening to have to google hard to figure out the root cause.  :-)

**Comment by crobinso** [comment]
@PenelopeFudd yes that's fair. Can you open a separate issue for that so we can track it and close it separately?
