### ISSUE TITLE
Can't run without systemd

### ISSUE THREAD

**Issue by Horhik** [virt-manager/virt-manager#183]
I'm using artix linux, and there's no systemd. I installed libvirt-openrc, but nothing could happend. virt-manager require running libvirtd daemon. How i can fix that?

Distro: **Artix linux**

**Comment by crobinso** [comment]
Thanks for the report. virt-manager shouldn't require systemd. What is the error you are seeing? Please provide the full output of `virt-manager --debug` when reproducing the error

**Comment by Horhik** [comment]
```
...
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (virtmanager:201) PyGObject version: 3.38.0
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (virtmanager:205) GTK version: 3.24.23
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (systray:73) AppIndicator3 is available, but didn't find any dbus watcher.
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (systray:463) Showing systray: False
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (inspection:206) python guestfs is not installed
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (engine:113) Loading stored URIs:
lxc:///
qemu:///system
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (engine:461) processing cli command uri= show_window=manager domain=
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (engine:464) No cli action requested, launching default window
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (manager:185) Showing manager
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (engine:316) window counter incremented to 1
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (engine:211) Initial gtkapplication activated
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (connection:482) conn=lxc:/// changed to state=Connecting
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (connection:902) Scheduling background open thread for lxc:///
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (connection:837) conn.close() uri=lxc:///
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (connection:482) conn=lxc:/// changed to state=Disconnected
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (engine:179) Autostart connection error: Unable to connect to libvirt lxc:///.

Verify that the 'libvirtd' daemon is running.

Libvirt URI is: lxc:///

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 922, in _do_open
    self._backend.open(cb, data)
  File "/usr/share/virt-manager/virtinst/connection.py", line 153, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/lib/python3.8/site-packages/libvirt.py", line 104, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (connection:482) conn=qemu:///system changed to state=Connecting
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (connection:902) Scheduling background open thread for qemu:///system
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (connection:837) conn.close() uri=qemu:///system
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (connection:482) conn=qemu:///system changed to state=Disconnected
[to, 12 marras 2020 17:23:55 virt-manager 13909] DEBUG (engine:179) Autostart connection error: Unable to connect to libvirt qemu:///system.

Verify that the 'libvirtd' daemon is running.

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 922, in _do_open
    self._backend.open(cb, data)
  File "/usr/share/virt-manager/virtinst/connection.py", line 153, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/lib/python3.8/site-packages/libvirt.py", line 104, in openAuth
    if ret is None:raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
```

**Comment by crobinso** [comment]
That error says system instance of libvirtd isn't running on your host. I don't know how openrc works or how your distro works. You need to start libvirtd if you want to manage VMs on your local machine. I can't really help you more than that, I suggest asking in your distro support channels

**Comment by Horhik** [comment]
Thanks

**Comment by Horhik** [comment]
I think, it's will be usefull to leave it here:
**The solution:**
austostarting libvirtd and virtlog
```bash 
rc-update add libvirtd
rc-update add virtlogd
```
