### ISSUE TITLE
Can not add host USB device -- retro-bit sega controller (8 button)

### ISSUE THREAD

**Issue by D33M0N** [virt-manager/virt-manager#202]
**Distro**: Manjaro

```
Unable to add device: internal error: vendor cannot be 0.

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/addhardware.py", line 1289, in _finish_cb
    failure = self._add_device(dev)
  File "/usr/share/virt-manager/virtManager/addhardware.py", line 1281, in _add_device
    self.vm.add_device(dev)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 580, in add_device
    self._redefine_xmlobj(xmlobj)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 383, in _redefine_xmlobj
    self._redefine_xml_internal(origxml, newxml)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 366, in _redefine_xml_internal
    self._define(newxml)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1065, in _define
    self.conn.define_domain(xml)
  File "/usr/share/virt-manager/virtManager/connection.py", line 554, in define_domain
    return self._backend.defineXML(xml)
  File "/usr/lib/python3.8/site-packages/libvirt.py", line 4048, in defineXML
    if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirt.libvirtError: internal error: vendor cannot be 0.
```

dunno what to do about it. dmesg messages when plugging the device in show some vendorID different than 0 (namely 0079):
```
[278124.325583] usb 1-1.4: new full-speed USB device number 9 using xhci_hcd
[278124.432598] usb 1-1.4: New USB device found, idVendor=0079, idProduct=0011, bcdDevice= 1.05
[278124.432601] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[278124.432603] usb 1-1.4: Product: USB Gamepad 
[278124.511022] input: USB Gamepad  as /devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.1/usb1/1-1/1-1.4/1-1.4:1.0/0003:0079:0011.000C/input/input30
[278124.511125] dragonrise 0003:0079:0011.000C: input,hidraw11: USB HID v1.10 Joystick [USB Gamepad ] on usb-0000:2a:00.1-1.4/input0
```

```
$ lsusb -v -s 009

Bus 001 Device 009: ID 0079:0011 DragonRise Inc. Gamepad
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x0079 DragonRise Inc.
  idProduct          0x0011 Gamepad
  bcdDevice            1.05
  iManufacturer           0 
  iProduct                2 USB Gamepad 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0022
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     101
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
```

**Comment by crobinso** [comment]
Thanks for the report. This is a libvirt bug though, it's fixed upstream. Here's a Fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1897625

If you are using a different distro, please file a bug with them and ask them to backport that fix. Or update to libvirt 6.10.0 which has the fix
