### ISSUE TITLE
Unable to open graphical console of running virtual machine

### ISSUE THREAD

**Issue by s-t-o-f-f-l** [virt-manager/virt-manager#226]
When trying to open graphical console or details window of a running virtual machine I get the following error message:

```
Fehler beim Starten der Details: Argument 1 does not allow None as a value

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 40, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 158, in __init__
    self.activate_default_page()
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 459, in activate_default_page
    self.activate_default_console_page()
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 451, in activate_default_console_page
    self._console.vmwindow_activate_default_console_page()
  File "/usr/share/virt-manager/virtManager/details/console.py", line 976, in vmwindow_activate_default_console_page
    return self._activate_default_console_page()
  File "/usr/share/virt-manager/virtManager/details/console.py", line 931, in _activate_default_console_page
    self._toggle_first_console_menu_item()
  File "/usr/share/virt-manager/virtManager/details/console.py", line 909, in _toggle_first_console_menu_item
    self._populate_console_list_menu()
  File "/usr/share/virt-manager/virtManager/details/console.py", line 904, in _populate_console_list_menu
    self._console_list_menu_toggled)
  File "/usr/share/virt-manager/virtManager/details/console.py", line 281, in rebuild_menu
    item.set_sensitive(sensitive)
TypeError: Argument 1 does not allow None as a value
```
I can open shutdown or not running VMs without any issue.

**Distro**: 3.2.0

**Comment by crobinso** [comment]
What linux distro are you using?
What is the pygobject3 (or python3-gi) version installed?
What is the gtk3 (or libgtk-3-0) version installed?

**Comment by s-t-o-f-f-l** [comment]
Debian 10 Buster - Kernel 4.19.0-14-amd64
python3-gi 3.30.4-1
python3-gi-cairo 3.30.4-1
libgtk-3-0:amd64 3.24.5-1
libgtk-3-bin 3.24.5-1
libgtk-3-common 3.24.5-1

**Comment by crobinso** [comment]
In git I just bumped the pygobject requirement to 3.13.0. Since two of these issues have already made their way in I'm guessing there are more lurking too. That release is 2 years old so not too limiting IMO

**Comment by s-t-o-f-f-l** [comment]
Thanks for solving this issue, for me it works now.
When you say that pygobject requirement is >= 3.31.0, how can I achieve to get this version on DEBIAN BUSTER?
I tried to get it through buster-backports but there is no backport version for pygobject.
Is there any way to update, because the dependencies on libc6 made me problems (My system crashed when updating libc6 some time ago)
Is it possible to download the .deb package from BULLSEYE (actually python3-gi version 3.38.0-2)? [https://packages.debian.org/bullseye/python3-gi](url)

**Comment by crobinso** [comment]
I don't know about Debian myself. You'll probably want to file a bug with them or ask in their support channels
