### ISSUE TITLE
Virt-Manager cannot connect when kvmgt kernel module is loaded

### ISSUE THREAD

**Issue by jason-600** [virt-manager/virt-manager#229]
**Distro**: Opensuse tumbleweed (KDE)
Bug: Virt-Manager cannot connect when kvmgt kernel module is loaded. 
virsh still works, vm's can be started and stopped.
virt-viewer still works for viewing a vm (using virt-viewer -a --connect qemu:///system win10gvt)
Unloading the module (sudo modprobe -r kvmgt) and restarting virt-manager allows it to connect again.

This is the debug info:
[Thu, 11 Feb 2021 20:07:24 virt-manager 30683] DEBUG (engine:299) Error polling connection qemu:///system
Traceback (most recent call last):
  File "./virtManager/engine.py", line 294, in _handle_tick_queue
    conn.tick_from_engine(**kwargs)
  File "./virtManager/connection.py", line 1321, in tick_from_engine
    self._tick(*args, **kwargs)
  File "./virtManager/connection.py", line 1204, in _tick
    self._hostinfo = self._backend.getInfo()
  File "/usr/lib64/python3.8/site-packages/libvirt.py", line 4538, in getInfo
    raise libvirtError('virNodeGetInfo() failed')
libvirt.libvirtError: internal error: client socket is closed
[Thu, 11 Feb 2021 20:07:24 virt-manager 30683] DEBUG (connection:851) Failed to deregister events in conn cleanup
Traceback (most recent call last):
  File "./virtManager/connection.py", line 843, in close
    self._backend.domainEventDeregisterAny(eid)
  File "/usr/lib64/python3.8/site-packages/libvirt.py", line 5823, in domainEventDeregisterAny
    raise libvirtError('virConnectDomainEventDeregisterAny() failed')
libvirt.libvirtError: internal error: client socket is closed
[Thu, 11 Feb 2021 20:07:24 virt-manager 30683] DEBUG (connection:876) LEAK: conn close() returned 1, meaning refs may have leaked.
[Thu, 11 Feb 2021 20:07:24 virt-manager 30683] DEBUG (connection:482) conn=qemu:///session changed to state=Disconnected
[Thu, 11 Feb 2021 20:07:24 virt-manager 30683] DEBUG (connection:837) conn.close() uri=qemu:///system
[Thu, 11 Feb 2021 20:07:24 virt-manager 30683] DEBUG (connection:851) Failed to deregister events in conn cleanup
Traceback (most recent call last):
  File "./virtManager/connection.py", line 843, in close
    self._backend.domainEventDeregisterAny(eid)
  File "/usr/lib64/python3.8/site-packages/libvirt.py", line 5823, in domainEventDeregisterAny
    raise libvirtError('virConnectDomainEventDeregisterAny() failed')
libvirt.libvirtError: internal error: client socket is closed
[Thu, 11 Feb 2021 20:07:24 virt-manager 30683] DEBUG (connection:876) LEAK: conn close() returned 1, meaning refs may have leaked.
[Thu, 11 Feb 2021 20:07:24 virt-manager 30683] DEBUG (connection:482) conn=qemu:///system changed to state=Disconnected

Note: kvmgt is a kernel module required for the intel gvt-g vgpu

Hope this helps, many thanks

Edit: Sorry, forgot to mention kernel version is 5.10.7, also rebooted with kernel version 5.9.14 with the same results

**Comment by crobinso** [comment]
`internal error: client socket is closed` usually means libvirtd is hanging or crashing. Does virt-manager fail the same way every time? Does it fail immediately or after some specific action? Does `virsh --connect qemu:///system nodeinfo` succeed when kvm-gt is loaded?

Maybe check `dmesg` output to see if there's any errors that look kernel issue related. It's unlikely this is specifically virt-manager related

**Comment by jason-600** [comment]
Virt-manager fails immediately and every time when kvmgt is loaded. I also tried loaded virt-manager without kvmgt, it started and showed the vms, then modprobe kvmgt, and virt-manager immediately disconnected. 

Output of virsh --connect qemu:///system nodeinfo

CPU model:           x86_64
CPU(s):              4
CPU frequency:       2399 MHz
CPU socket(s):       1
Core(s) per socket:  2
Thread(s) per core:  2
NUMA cell(s):        1
Memory size:         12118472 KiB

Output of dmesg

[102515.240629] VFIO - User Level meta-driver version: 0.3
[102515.260741] i915 0000:00:02.0: MDEV: Registered
[102515.274312] vfio_mdev fda6cb3d-8d67-4c44-830f-6b998206e8f2: Adding to iommu group 0
[102515.274314] vfio_mdev fda6cb3d-8d67-4c44-830f-6b998206e8f2: MDEV: group_id = 0
[102582.170900] show_signal_msg: 55 callbacks suppressed
[102582.170902] rpc-worker[27398]: segfault at 2 ip 00007f5a291bf418 sp 00007f5a26734730 error 4 in libvirt.so.0.6010.0[7f5a29094000+278000]
[102582.170910] Code: 44 24 18 31 c0 48 83 3a 00 48 c7 44 24 10 00 00 00 00 48 c7 44 24 08 00 00 00 00 74 1b 31 db 0f 1f 00 49 8b 04 dc 48 83 c3 01 <48> 8b 38 e8 f0 a1 ed ff 48 39 5d 00 77 ea 49 8b 3c 24 48 85 ff 74
[102582.234096] rpc-worker[26869]: segfault at 2 ip 00007f85fdf57418 sp 00007f85fa9fe730 error 4 in libvirt.so.0.6010.0[7f85fde2c000+278000]
[102582.234106] Code: 44 24 18 31 c0 48 83 3a 00 48 c7 44 24 10 00 00 00 00 48 c7 44 24 08 00 00 00 00 74 1b 31 db 0f 1f 00 49 8b 04 dc 48 83 c3 01 <48> 8b 38 e8 f0 a1 ed ff 48 39 5d 00 77 ea 49 8b 3c 24 48 85 ff 74

Hope this helps, thank you

**Comment by crobinso** [comment]
`rpc-worker` is the name of a thread in libvirtd. so it looks like libvirtd is crashing which confirms my original guess. To get more info you'll want to try getting a gdb backtrace out of libvirtd, or using coredumpctl to get that if your distro has that configured. This doesn't look like a virt-manager specific problem though, so I'm closing this

**Comment by jason-600** [comment]
Update: after updating Opensuse Tumbleweed today (Kernel 5.10.16), virt-manager is now working correctly with kvmgt kernel module. Not sure what specifically fixed it.

Many thanks for you help.
