### ISSUE TITLE
ModuleNotFoundError: No module named 'idna'

### ISSUE THREAD

**Issue by sadransh** [virt-manager/virt-manager#231]
**Distro**:  Ubuntu 20.04 
tested with apt-get version and also colned version from here : 

```
Traceback (most recent call last):
  File "./virt-manager", line 8, in <module>
    from virtManager import virtmanager
  File "./virtManager/virtmanager.py", line 19, in <module>
    from virtinst import BuildConfig
  File "./virtinst/__init__.py", line 60, in <module>
    from virtinst.install.installer import Installer
  File "./virtinst/install/installer.py", line 12, in <module>
    from . import unattended
  File "./virtinst/install/unattended.py", line 18, in <module>
    from . import urlfetcher
  File "./virtinst/install/urlfetcher.py", line 16, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 113, in <module>
    from . import packages
  File "/usr/lib/python3/dist-packages/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
ModuleNotFoundError: No module named 'idna'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 113, in <module>
    from . import packages
  File "/usr/lib/python3/dist-packages/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
ModuleNotFoundError: No module named 'idna'

Original exception was:
Traceback (most recent call last):
  File "./virt-manager", line 8, in <module>
    from virtManager import virtmanager
  File "./virtManager/virtmanager.py", line 19, in <module>
    from virtinst import BuildConfig
  File "./virtinst/__init__.py", line 60, in <module>
    from virtinst.install.installer import Installer
  File "./virtinst/install/installer.py", line 12, in <module>
    from . import unattended
  File "./virtinst/install/unattended.py", line 18, in <module>
    from . import urlfetcher
  File "./virtinst/install/urlfetcher.py", line 16, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 113, in <module>
    from . import packages
  File "/usr/lib/python3/dist-packages/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
ModuleNotFoundError: No module named 'idna'
```

**Comment by crobinso** [comment]
Thanks for the report. Something is wrong with your 'requests` install, in my experience this is usually a mismatch between something installed by your host package manager and remnants of a version left over from a pip install. It could be ubuntu packages missing a dependency somewhere too but I think that's less likely. Either way this is unlikely to be a virt-manager issue
