### ISSUE TITLE
host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]

### ISSUE THREAD

**Issue by xekon** [virt-manager/virt-manager#235]
**Distro**: Ubuntu 20.04.2 LTS (Focal Fossa)
**Kernel**: 5.10.23-xanmod1 x86_64
**Desktop**: KDE Plasma 5.18.5
**CPU**: e3-1275v2
**Motherboard**: Supermicro X9SAE

These features seem to not be working:
MSR(48DH).vmx-posted-intr [bit 7]
MSR(48BH).vmx-apicv-register [bit 8]
MSR(48BH).vmx-apicv-vid [bit 9]

With the research I have done so far I found a related report on the kubevirt project: https://github.com/kubevirt/kubevirt/issues/3587

The user that filled the report said this:

_Adding a CPU model like Haswell--noTSX-IBRS solves the issue. I wonder why qemu does not detect the correct CPU features, though, as it has the cpu set to host-model and does some additional checking of features as well._

My cpu is not a Haswell, its a xeon, however I would like to try adding a CPU model once I figure out where to put this information into virt-manager and I also need to figure out the correct cpu model for my cpu, surely its not just xeon, there are tons of variations of those.

Here is the details log from virt-manager when I was attempting to create a new VM.
```
Unable to complete install: 'internal error: process exited while connecting to monitor: 2021-03-12T18:24:28.949747Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2021-03-12T18:24:28.950415Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-register [bit 8]
2021-03-12T18:24:28.950422Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]
2021-03-12T18:24:28.950426Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2021-03-12T18:24:29.401942Z qemu-system-x86_64: -device vfio-pci,host=0000:02:00.0,id=hostdev2,bus=pci.3,addr=0x0: vfio 0000:02:00.0: group 1 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2089, in _do_async_install
    guest.installer_instance.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 542, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 491, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4034, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2021-03-12T18:24:28.949747Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2021-03-12T18:24:28.950415Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-register [bit 8]
2021-03-12T18:24:28.950422Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48BH).vmx-apicv-vid [bit 9]
2021-03-12T18:24:28.950426Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48DH).vmx-posted-intr [bit 7]
2021-03-12T18:24:29.401942Z qemu-system-x86_64: -device vfio-pci,host=0000:02:00.0,id=hostdev2,bus=pci.3,addr=0x0: vfio 0000:02:00.0: group 1 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
```

**Comment by xekon** [comment]
sorry, the github page actually timed out when I created this request, and it appears to have double posted.
