### ISSUE TITLE
libosinfo: Unexpected file type (0)

### ISSUE THREAD

**Issue by tnynyn** [virt-manager/virt-manager#248]
Getting this error when trying to open the VM details (as well as creating a new vm).. happened after upgrading from Ubuntu 18.04 to 20.04:

```
Error launching details: libosinfo: Unexpected file type (0)

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 39, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 76, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
  File "/usr/share/virt-manager/virtManager/details/details.py", line 447, in __init__
    self.init_details()
  File "/usr/share/virt-manager/virtManager/details/details.py", line 774, in init_details
    self._os_list = vmmOSList()
  File "/usr/share/virt-manager/virtManager/oslist.py", line 39, in __init__
    self._init_state()
  File "/usr/share/virt-manager/virtManager/oslist.py", line 55, in _init_state
    all_os = virtinst.OSDB.list_os()
  File "/usr/share/virt-manager/virtinst/osdict.py", line 274, in list_os
    for name, osobj in self._all_variants.items():
  File "/usr/share/virt-manager/virtinst/osdict.py", line 198, in _all_variants
    loader = self._os_loader
  File "/usr/share/virt-manager/virtinst/osdict.py", line 190, in _os_loader
    loader.process_default_path()
gi.repository.GLib.GError: libosinfo: Unexpected file type (0)
```

EDIT:  Debug info:

```
[Wed, 05 May 2021 09:55:10 virt-manager 97716] DEBUG (xmleditor:12) Using GtkSource 4
[Wed, 05 May 2021 09:55:10 virt-manager 97716] DEBUG (serialcon:17) Using VTE API 2.91
[Wed, 05 May 2021 09:55:10 virt-manager 97716] DEBUG (error:84) error dialog message:
summary=Error launching details: libosinfo: Unexpected file type (0)
details=Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 39, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 76, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
  File "/usr/share/virt-manager/virtManager/details/details.py", line 447, in __init__
    self.init_details()
  File "/usr/share/virt-manager/virtManager/details/details.py", line 774, in init_details
    self._os_list = vmmOSList()
  File "/usr/share/virt-manager/virtManager/oslist.py", line 39, in __init__
    self._init_state()
  File "/usr/share/virt-manager/virtManager/oslist.py", line 55, in _init_state
    all_os = virtinst.OSDB.list_os()
  File "/usr/share/virt-manager/virtinst/osdict.py", line 274, in list_os
    for name, osobj in self._all_variants.items():
  File "/usr/share/virt-manager/virtinst/osdict.py", line 198, in _all_variants
    loader = self._os_loader
  File "/usr/share/virt-manager/virtinst/osdict.py", line 190, in _os_loader
    loader.process_default_path()
gi.repository.GLib.GError: libosinfo: Unexpected file type (0)
[Wed, 05 May 2021 09:55:10 virt-manager 97716] DEBUG (cli:199) Uncaught exception:
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/manager.py", line 489, in row_activated
    self.show_vm(_src)
  File "/usr/share/virt-manager/virtManager/manager.py", line 474, in show_vm
    vmmenu.VMActionUI.show(self, self.current_vm())
  File "/usr/share/virt-manager/virtManager/vmmenu.py", line 330, in show
    vmmVMWindow.get_instance(src, vm).show()
AttributeError: 'NoneType' object has no attribute 'show'
```

I tried removing / reinstalling virt-manager and libosinfo, updating to latest version 3.2, but same error.   Have two other boxes setup and upgraded the same way, but those are working fine.. Any ideas?

**Comment by tnynyn** [comment]
Nevermind, fixed it...had the wrong permissions on ~/.config   if anyone else runs into this issue
