### ISSUE TITLE
Ubuntu 20.04 - ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by Bobses** [virt-manager/virt-manager#268]
**Distro**: Ubuntu 20.04

Cannot start Virtual Manager in Ubuntu 20.04. This is a recent behavior, probably after the package or distribution upgrade.

`$ virt-manager`

> Traceback (most recent call last):
>   File "/usr/share/virt-manager/virt-manager", line 19, in <module>
>     from virtinst import BuildConfig
>   File "/usr/share/virt-manager/virtinst/__init__.py", line 49, in <module>
>     from virtinst.domain import *  # pylint: disable=wildcard-import
>   File "/usr/share/virt-manager/virtinst/domain/__init__.py", line 5, in <module>
>     from .blkiotune import DomainBlkiotune
>   File "/usr/share/virt-manager/virtinst/domain/blkiotune.py", line 8, in <module>
>     from ..xmlbuilder import XMLBuilder, XMLChildProperty, XMLProperty
>   File "/usr/share/virt-manager/virtinst/xmlbuilder.py", line 16, in <module>
>     from .xmlapi import XMLAPI
>   File "/usr/share/virt-manager/virtinst/xmlapi.py", line 7, in <module>
>     import libxml2
> ValueError: source code string cannot contain null bytes

And the latest packages upgraded:

`$ grep "upgrade " /var/log/dpkg.log | grep virt`

> 2021-06-24 21:49:55 upgrade libvirt-daemon-driver-qemu:amd64 6.0.0-0ubuntu8.9 6.0.0-0ubuntu8.10
> 2021-06-24 21:49:55 upgrade libvirt-daemon-driver-storage-rbd:amd64 6.0.0-0ubuntu8.9 6.0.0-0ubuntu8.10
> 2021-06-24 21:49:55 upgrade libvirt-daemon-system:amd64 6.0.0-0ubuntu8.9 6.0.0-0ubuntu8.10
> 2021-06-24 21:49:56 upgrade libvirt-clients:amd64 6.0.0-0ubuntu8.9 6.0.0-0ubuntu8.10
> 2021-06-24 21:49:56 upgrade libvirt0:amd64 6.0.0-0ubuntu8.9 6.0.0-0ubuntu8.10
> 2021-06-24 21:49:57 upgrade libvirt-daemon:amd64 6.0.0-0ubuntu8.9 6.0.0-0ubuntu8.10
> 2021-06-24 21:49:57 upgrade libvirt-daemon-system-systemd:amd64 6.0.0-0ubuntu8.9 6.0.0-0ubuntu8.10
> 2021-06-25 10:49:29 upgrade libvirt-daemon:amd64 6.0.0-0ubuntu8.10 6.0.0-0ubuntu8.10
> 2021-06-25 10:49:29 upgrade virt-manager:all 1:2.2.1-3ubuntu2.1 1:2.2.1-3ubuntu2.1
> 2021-06-25 10:49:30 upgrade virtinst:all 1:2.2.1-3ubuntu2.1 1:2.2.1-3ubuntu2.1

**Comment by crobinso** [comment]
This looks like it's erroring on importing libxml2. Does the command `python -c 'import libxml2'` fail similarly? If so you need to file a bug with your distro

**Comment by Bobses** [comment]
Ok, thanks, seems that the below command  fails in the same way:

`python3 -c 'import libxml2'`

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ValueError: source code string cannot contain null bytes

**Comment by crobinso** [comment]
Thanks for confirming. Something seems very wrong with your install of libxml2
