### ISSUE TITLE
Failed to connect socket Unsure what I'm doing wrong

### ISSUE THREAD

**Issue by PeterKW** [virt-manager/virt-manager#298]
`Failed to connect socket to '/var/run/libvirt/virtqemud-sock': Connection refused`

I tried to use gnome-boxes vm manager as well and couldn't get it to work. Is there any way of debugging what the problem could be with my setup further? I'm not quite sure what else to try

```
Unable to connect to libvirt qemu:///system.

Failed to connect socket to '/var/run/libvirt/virtqemud-sock': Connection refused

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 922, in _do_open
    self._backend.open(cb, data)
  File "/usr/share/virt-manager/virtinst/connection.py", line 153, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/lib/python3.9/site-packages/libvirt.py", line 148, in openAuth
    raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/virtqemud-sock': Connection refused
```

**Comment by phrdina** [comment]
Hi, can you please provide your OS, virt-manager version and exact steps to reproduce the issue?

**Comment by WillNilges** [comment]
What was the solution to this issue?
