### ISSUE TITLE
"TypeError: could not get a reference to type class"

### ISSUE THREAD

**Issue by DUOLabs333** [virt-manager/virt-manager#309]
I'm using MacPorts, though the actually code I just downloaded from git. It loads up fine, but when I try to do anything (for example, open up the 'test' virtual machine), it gives the error "TypeError: could not get a reference to type class". The full traceback is as such:
```
Error launching details: could not get a reference to type class

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/vmwindow.py", line 40, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/vmwindow.py", line 82, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/details/details.py", line 397, in __init__
    self._xmleditor = vmmXMLEditor(self.builder, self.topwin,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/xmleditor.py", line 44, in __init__
    self._init_ui()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/xmleditor.py", line 69, in _init_ui
    self._srcview = GtkSource.View()
TypeError: could not get a reference to type class
```

**Comment by DUOLabs333** [comment]
Using `--no-fork` gives me
```
Failed to load shared library 'libgtksourceview-4.0.dylib' referenced by the typelib: dlopen(libgtksourceview-4.0.dylib, 9): image not found
/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/xmleditor.py:69: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  self._srcview = GtkSource.View()
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/vmmenu.py", line 47, in _cb
    return cb(self._parent, _vm)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/vmmenu.py", line 324, in show
    vmmVMWindow.get_instance(src, vm).show()
AttributeError: 'NoneType' object has no attribute 'show'
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/details/details.py", line 363, in signal_cb
    self._enable_apply(edittype)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/share/virt-manager/virtManager/details/details.py", line 1304, in _enable_apply
    self._xmleditor.details_changed = True
AttributeError: 'vmmDetails' object has no attribute '_xmleditor'
```

**Comment by DUOLabs333** [comment]
Solved: use `DYLD_FALLBACK_LIBRARY_PATH=/opt/local/lib virt-manager`
