### ISSUE TITLE
Virtual Machine Details - Error launching details: Unknown address type

### ISSUE THREAD

**Issue by Toby4213** [virt-manager/virt-manager#328]
**Distro**: Pop!_OS 21.04

I create a VM with PCIe Passthough successfully. I cloned the VM, without copying the disk because I wanted a second config without PCIe Passthrough. The cloning worked, after that I wanted to change the config of the cloned VM but got the following error for both the Cloned and original VM when I try to open the Virtual Machine Details: `Error launching details: Unknown address type`
<details>
  <summary>Details</summary>

  ```
    Traceback (most recent call last):
    File "/home/toby/Workspace/virt-manager/./virtManager/vmwindow.py", line 40, in get_instance
      cls._instances[key] = vmmVMWindow(vm)
    File "/home/toby/Workspace/virt-manager/./virtManager/vmwindow.py", line 82, in __init__
      self._details = vmmDetails(self.vm, self.builder, self.topwin,
    File "/home/toby/Workspace/virt-manager/./virtManager/details/details.py", line 377, in __init__
      self.gfxdetails = vmmGraphicsDetails(
    File "/home/toby/Workspace/virt-manager/./virtManager/device/gfxdetails.py", line 56, in __init__
      self._init_ui()
    File "/home/toby/Workspace/virt-manager/./virtManager/device/gfxdetails.py", line 118, in _init_ui
      model.append([rendernode, i.pretty_name()])
    File "/home/toby/Workspace/virt-manager/./virtManager/object/nodedev.py", line 62, in pretty_name
      return _pretty_name(self.xmlobj)
    File "/home/toby/Workspace/virt-manager/./virtManager/object/nodedev.py", line 38, in _pretty_name
      parent = NodeDevice.lookupNodedevFromString(
    File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 79, in lookupNodedevFromString
      return _AddressStringToNodedev(conn, idstring)
    File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 247, in _AddressStringToNodedev
      hostdev = _AddressStringToHostdev(conn, addrstr)
    File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 238, in _AddressStringToHostdev
      raise RuntimeError("Unknown address type")
  RuntimeError: Unknown address type
  ```
</details>

I investigated the issue a bit and found that the error is because in the file nodedev.py@line 172 the function variable addrstr contains the string `pci_0000_09_00_0`. I have no idea where this comes from. I searched for that string with this command `grep -r 'pci_0000_09_00_0' /etc/libvirt/` and the only occurrence is in /etc/libvirt/hooks/kvm.conf. Even if I remove that file the error occurs.
<details>
  <summary>kvm.conf</summary>

  ```
  ## Virsh devices
VIRSH_GPU_VIDEO=pci_0000_09_00_0
VIRSH_GPU_AUDIO=pci_0000_09_00_1
VIRSH_GPU_USB=pci_0000_09_00_2
VIRSH_GPU_SERIAL=pci_0000_09_00_3
  ```
</details>
kvm.conf used in the prepare and release script to bind/unbind the gpu.

I also manually removed all pcie devices from the xml `sudo virsh edit win10gaming` but this also didn't change anything.

<details>
  <summary>virt-manager debug output</summary>

  ```
  toby@vega ~/W/virt-manager (master)> ./virt-manager --debug
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (cli:204) Launched with command line: ./virt-manager --debug
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (virtmanager:167) virt-manager version: 3.2.0
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (virtmanager:168) virtManager import: /home/toby/Workspace/virt-manager/./virtManager
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (virtmanager:205) PyGObject version: 3.38.0
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (virtmanager:209) GTK version: 3.24.25
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (systray:84) Imported AppIndicator3=<IntrospectionModule 'AyatanaAppIndicator3' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/AyatanaAppIndicator3-0.1.typelib'>
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (systray:90) Using AppIndicator3 for systray
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (systray:476) Showing systray: False
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (inspection:206) python guestfs is not installed
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (engine:113) Loading stored URIs:
qemu:///system
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (engine:461) processing cli command uri= show_window=manager domain=
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (engine:464) No cli action requested, launching default window
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (manager:185) Showing manager
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (engine:316) window counter incremented to 1
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (engine:211) Initial gtkapplication activated
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (connection:482) conn=qemu:///system changed to state=Connecting
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (connection:902) Scheduling background open thread for qemu:///system
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (connection:952) libvirt version=7000000
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (connection:953) daemon version=7000000
[Thu, 18 Nov 2021 15:51:46 virt-manager 43336] DEBUG (connection:954) conn version=5002000
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:955) qemu:///system capabilities:
<capabilities>
 
  <host>
    <uuid>0a9c22cc-276c-11b2-a85c-96de57fc7098</uuid>
    <cpu>
      <arch>x86_64</arch>
      <model>Skylake-Client-noTSX-IBRS</model>
      <vendor>Intel</vendor>
      <microcode version="234"/>
      <counter name="tsc" frequency="1991998000" scaling="no"/>
      <topology sockets="1" dies="1" cores="4" threads="2"/>
      <feature name="ds"/>
      <feature name="acpi"/>
      <feature name="ss"/>
      <feature name="ht"/>
      <feature name="tm"/>
      <feature name="pbe"/>
      <feature name="dtes64"/>
      <feature name="monitor"/>
      <feature name="ds_cpl"/>
      <feature name="vmx"/>
      <feature name="est"/>
      <feature name="tm2"/>
      <feature name="xtpr"/>
      <feature name="pdcm"/>
      <feature name="osxsave"/>
      <feature name="tsc_adjust"/>
      <feature name="clflushopt"/>
      <feature name="intel-pt"/>
      <feature name="md-clear"/>
      <feature name="stibp"/>
      <feature name="ssbd"/>
      <feature name="xsaves"/>
      <feature name="pdpe1gb"/>
      <feature name="invtsc"/>
      <pages unit="KiB" size="4"/>
      <pages unit="KiB" size="2048"/>
      <pages unit="KiB" size="1048576"/>
    </cpu>
    <power_management>
      <suspend_mem/>
      <suspend_disk/>
      <suspend_hybrid/>
    </power_management>
    <iommu support="yes"/>
    <migration_features>
      <live/>
      <uri_transports>
        <uri_transport>tcp</uri_transport>
        <uri_transport>rdma</uri_transport>
      </uri_transports>
    </migration_features>
    <topology>
      <cells num="1">
        <cell id="0">
          <memory unit="KiB">16147204</memory>
          <pages unit="KiB" size="4">4036801</pages>
          <pages unit="KiB" size="2048">0</pages>
          <pages unit="KiB" size="1048576">0</pages>
          <distances>
            <sibling id="0" value="10"/>
          </distances>
          <cpus num="8">
            <cpu id="0" socket_id="0" die_id="0" core_id="0" siblings="0,4"/>
            <cpu id="1" socket_id="0" die_id="0" core_id="1" siblings="1,5"/>
            <cpu id="2" socket_id="0" die_id="0" core_id="2" siblings="2,6"/>
            <cpu id="3" socket_id="0" die_id="0" core_id="3" siblings="3,7"/>
            <cpu id="4" socket_id="0" die_id="0" core_id="0" siblings="0,4"/>
            <cpu id="5" socket_id="0" die_id="0" core_id="1" siblings="1,5"/>
            <cpu id="6" socket_id="0" die_id="0" core_id="2" siblings="2,6"/>
            <cpu id="7" socket_id="0" die_id="0" core_id="3" siblings="3,7"/>
          </cpus>
        </cell>
      </cells>
    </topology>
    <cache>
      <bank id="0" level="3" type="both" size="8" unit="MiB" cpus="0-7"/>
    </cache>
    <secmodel>
      <model>apparmor</model>
      <doi>0</doi>
    </secmodel>
    <secmodel>
      <model>dac</model>
      <doi>0</doi>
      <baselabel type="kvm">+64055:+108</baselabel>
      <baselabel type="qemu">+64055:+108</baselabel>
    </secmodel>
  </host>
 
  <guest>
    <os_type>hvm</os_type>
    <arch name="i686">
      <wordsize>32</wordsize>
      <emulator>/usr/bin/qemu-system-i386</emulator>
      <machine maxCpus="255">pc-i440fx-hirsute</machine>
      <machine canonical="pc-i440fx-hirsute" maxCpus="255">ubuntu</machine>
      <machine maxCpus="288">pc-q35-5.2</machine>
      <machine canonical="pc-q35-5.2" maxCpus="288">q35</machine>
      <machine maxCpus="255">pc-i440fx-2.12</machine>
      <machine maxCpus="255">pc-i440fx-2.0</machine>
      <machine maxCpus="255">pc-i440fx-xenial</machine>
      <machine maxCpus="288">pc-q35-4.2</machine>
      <machine maxCpus="255">pc-i440fx-2.5</machine>
      <machine maxCpus="255">pc-i440fx-4.2</machine>
      <machine maxCpus="255">pc-i440fx-focal</machine>
      <machine maxCpus="255">pc-q35-xenial</machine>
      <machine maxCpus="255">pc-i440fx-5.2</machine>
      <machine canonical="pc-i440fx-5.2" maxCpus="255">pc</machine>
      <machine maxCpus="255">pc-i440fx-1.5</machine>
      <machine maxCpus="255">pc-q35-2.7</machine>
      <machine maxCpus="288">pc-q35-eoan-hpb</machine>
      <machine maxCpus="255">pc-i440fx-zesty</machine>
      <machine maxCpus="255">pc-i440fx-disco-hpb</machine>
      <machine maxCpus="288">pc-q35-groovy</machine>
      <machine maxCpus="255">pc-i440fx-groovy</machine>
      <machine maxCpus="288">pc-q35-artful</machine>
      <machine maxCpus="255">pc-i440fx-2.2</machine>
      <machine maxCpus="255">pc-i440fx-trusty</machine>
      <machine maxCpus="255">pc-i440fx-eoan-hpb</machine>
      <machine maxCpus="288">pc-q35-focal-hpb</machine>
      <machine maxCpus="255">pc-1.1</machine>
      <machine maxCpus="288">pc-q35-bionic-hpb</machine>
      <machine maxCpus="255">pc-i440fx-artful</machine>
      <machine maxCpus="255">pc-i440fx-2.7</machine>
      <machine maxCpus="255">pc-i440fx-yakkety</machine>
      <machine maxCpus="255">pc-q35-2.4</machine>
      <machine maxCpus="288">pc-q35-cosmic-hpb</machine>
      <machine maxCpus="288">pc-q35-2.10</machine>
      <machine maxCpus="255">pc-i440fx-1.7</machine>
      <machine maxCpus="288">pc-q35-5.1</machine>
      <machine maxCpus="288">pc-q35-2.9</machine>
      <machine maxCpus="255">pc-i440fx-2.11</machine>
      <machine maxCpus="288">pc-q35-3.1</machine>
      <machine maxCpus="288">pc-q35-4.1</machine>
      <machine maxCpus="255">pc-i440fx-2.4</machine>
      <machine maxCpus="255">pc-1.3</machine>
      <machine maxCpus="255">pc-i440fx-4.1</machine>
      <machine maxCpus="288">pc-q35-eoan</machine>
      <machine maxCpus="255">pc-i440fx-5.1</machine>
      <machine maxCpus="255">pc-i440fx-2.9</machine>
      <machine maxCpus="255">pc-i440fx-bionic-hpb</machine>
      <machine maxCpus="1">isapc</machine>
      <machine maxCpus="255">pc-i440fx-1.4</machine>
      <machine maxCpus="288">pc-q35-cosmic</machine>
      <machine maxCpus="255">pc-q35-2.6</machine>
      <machine maxCpus="255">pc-i440fx-3.1</machine>
      <machine maxCpus="288">pc-q35-bionic</machine>
      <machine maxCpus="288">pc-q35-disco-hpb</machine>
      <machine maxCpus="255">pc-i440fx-cosmic</machine>
      <machine maxCpus="288">pc-q35-2.12</machine>
      <machine maxCpus="255">pc-i440fx-bionic</machine>
      <machine maxCpus="288">pc-q35-groovy-hpb</machine>
      <machine maxCpus="288">pc-q35-disco</machine>
      <machine maxCpus="255">pc-i440fx-cosmic-hpb</machine>
      <machine maxCpus="255">pc-i440fx-2.1</machine>
      <machine maxCpus="255">pc-1.0</machine>
      <machine maxCpus="255">pc-i440fx-wily</machine>
      <machine maxCpus="255">pc-i440fx-2.6</machine>
      <machine maxCpus="288">pc-q35-hirsute</machine>
      <machine canonical="pc-q35-hirsute" maxCpus="288">ubuntu-q35</machine>
      <machine maxCpus="288">pc-q35-4.0.1</machine>
      <machine maxCpus="288">pc-q35-hirsute-hpb</machine>
      <machine maxCpus="255">pc-i440fx-1.6</machine>
      <machine maxCpus="288">pc-q35-5.0</machine>
      <machine maxCpus="288">pc-q35-2.8</machine>
      <machine maxCpus="255">pc-i440fx-2.10</machine>
      <machine maxCpus="288">pc-q35-3.0</machine>
      <machine maxCpus="288">pc-q35-zesty</machine>
      <machine maxCpus="288">pc-q35-4.0</machine>
      <machine maxCpus="288">microvm</machine>
      <machine maxCpus="255">pc-i440fx-2.3</machine>
      <machine maxCpus="288">pc-q35-focal</machine>
      <machine maxCpus="255">pc-i440fx-disco</machine>
      <machine maxCpus="255">pc-1.2</machine>
      <machine maxCpus="255">pc-i440fx-4.0</machine>
      <machine maxCpus="255">pc-i440fx-focal-hpb</machine>
      <machine maxCpus="255">pc-i440fx-groovy-hpb</machine>
      <machine maxCpus="255">pc-i440fx-hirsute-hpb</machine>
      <machine maxCpus="255">pc-i440fx-5.0</machine>
      <machine maxCpus="255">pc-i440fx-2.8</machine>
      <machine maxCpus="255">pc-i440fx-eoan</machine>
      <machine maxCpus="255">pc-q35-2.5</machine>
      <machine maxCpus="255">pc-i440fx-3.0</machine>
      <machine maxCpus="255">pc-q35-yakkety</machine>
      <machine maxCpus="288">pc-q35-2.11</machine>
      <domain type="qemu"/>
      <domain type="kvm"/>
    </arch>
    <features>
      <pae/>
      <nonpae/>
      <acpi default="on" toggle="yes"/>
      <apic default="on" toggle="no"/>
      <cpuselection/>
      <deviceboot/>
      <disksnapshot default="on" toggle="no"/>
    </features>
  </guest>
 
  <guest>
    <os_type>hvm</os_type>
    <arch name="x86_64">
      <wordsize>64</wordsize>
      <emulator>/usr/bin/qemu-system-x86_64</emulator>
      <machine maxCpus="255">pc-i440fx-hirsute</machine>
      <machine canonical="pc-i440fx-hirsute" maxCpus="255">ubuntu</machine>
      <machine maxCpus="288">pc-q35-5.2</machine>
      <machine canonical="pc-q35-5.2" maxCpus="288">q35</machine>
      <machine maxCpus="255">pc-i440fx-2.12</machine>
      <machine maxCpus="255">pc-i440fx-2.0</machine>
      <machine maxCpus="255">pc-i440fx-xenial</machine>
      <machine maxCpus="288">pc-q35-4.2</machine>
      <machine maxCpus="255">pc-i440fx-2.5</machine>
      <machine maxCpus="255">pc-i440fx-4.2</machine>
      <machine maxCpus="255">pc-i440fx-focal</machine>
      <machine maxCpus="255">pc-q35-xenial</machine>
      <machine maxCpus="255">pc-i440fx-5.2</machine>
      <machine canonical="pc-i440fx-5.2" maxCpus="255">pc</machine>
      <machine maxCpus="255">pc-i440fx-1.5</machine>
      <machine maxCpus="255">pc-q35-2.7</machine>
      <machine maxCpus="288">pc-q35-eoan-hpb</machine>
      <machine maxCpus="255">pc-i440fx-zesty</machine>
      <machine maxCpus="255">pc-i440fx-disco-hpb</machine>
      <machine maxCpus="288">pc-q35-groovy</machine>
      <machine maxCpus="255">pc-i440fx-groovy</machine>
      <machine maxCpus="288">pc-q35-artful</machine>
      <machine maxCpus="255">pc-i440fx-trusty</machine>
      <machine maxCpus="255">pc-i440fx-2.2</machine>
      <machine maxCpus="288">pc-q35-focal-hpb</machine>
      <machine maxCpus="255">pc-i440fx-eoan-hpb</machine>
      <machine maxCpus="255">pc-1.1</machine>
      <machine maxCpus="255">pc-i440fx-artful</machine>
      <machine maxCpus="288">pc-q35-bionic-hpb</machine>
      <machine maxCpus="255">pc-i440fx-2.7</machine>
      <machine maxCpus="255">pc-i440fx-yakkety</machine>
      <machine maxCpus="255">pc-q35-2.4</machine>
      <machine maxCpus="288">pc-q35-cosmic-hpb</machine>
      <machine maxCpus="288">pc-q35-2.10</machine>
      <machine maxCpus="255">pc-i440fx-1.7</machine>
      <machine maxCpus="288">pc-q35-5.1</machine>
      <machine maxCpus="288">pc-q35-2.9</machine>
      <machine maxCpus="255">pc-i440fx-2.11</machine>
      <machine maxCpus="288">pc-q35-3.1</machine>
      <machine maxCpus="288">pc-q35-4.1</machine>
      <machine maxCpus="255">pc-i440fx-2.4</machine>
      <machine maxCpus="255">pc-1.3</machine>
      <machine maxCpus="255">pc-i440fx-4.1</machine>
      <machine maxCpus="288">pc-q35-eoan</machine>
      <machine maxCpus="255">pc-i440fx-5.1</machine>
      <machine maxCpus="255">pc-i440fx-2.9</machine>
      <machine maxCpus="255">pc-i440fx-bionic-hpb</machine>
      <machine maxCpus="1">isapc</machine>
      <machine maxCpus="255">pc-i440fx-1.4</machine>
      <machine maxCpus="288">pc-q35-cosmic</machine>
      <machine maxCpus="255">pc-q35-2.6</machine>
      <machine maxCpus="255">pc-i440fx-3.1</machine>
      <machine maxCpus="288">pc-q35-bionic</machine>
      <machine maxCpus="288">pc-q35-disco-hpb</machine>
      <machine maxCpus="255">pc-i440fx-cosmic</machine>
      <machine maxCpus="288">pc-q35-2.12</machine>
      <machine maxCpus="255">pc-i440fx-bionic</machine>
      <machine maxCpus="288">pc-q35-groovy-hpb</machine>
      <machine maxCpus="288">pc-q35-disco</machine>
      <machine maxCpus="255">pc-i440fx-cosmic-hpb</machine>
      <machine maxCpus="255">pc-i440fx-2.1</machine>
      <machine maxCpus="255">pc-1.0</machine>
      <machine maxCpus="255">pc-i440fx-wily</machine>
      <machine maxCpus="255">pc-i440fx-2.6</machine>
      <machine maxCpus="288">pc-q35-hirsute</machine>
      <machine canonical="pc-q35-hirsute" maxCpus="288">ubuntu-q35</machine>
      <machine maxCpus="288">pc-q35-4.0.1</machine>
      <machine maxCpus="288">pc-q35-hirsute-hpb</machine>
      <machine maxCpus="255">pc-i440fx-1.6</machine>
      <machine maxCpus="288">pc-q35-5.0</machine>
      <machine maxCpus="288">pc-q35-2.8</machine>
      <machine maxCpus="255">pc-i440fx-2.10</machine>
      <machine maxCpus="288">pc-q35-3.0</machine>
      <machine maxCpus="288">pc-q35-zesty</machine>
      <machine maxCpus="288">pc-q35-4.0</machine>
      <machine maxCpus="288">microvm</machine>
      <machine maxCpus="288">pc-q35-focal</machine>
      <machine maxCpus="255">pc-i440fx-2.3</machine>
      <machine maxCpus="255">pc-i440fx-focal-hpb</machine>
      <machine maxCpus="255">pc-1.2</machine>
      <machine maxCpus="255">pc-i440fx-4.0</machine>
      <machine maxCpus="255">pc-i440fx-disco</machine>
      <machine maxCpus="255">pc-i440fx-groovy-hpb</machine>
      <machine maxCpus="255">pc-i440fx-hirsute-hpb</machine>
      <machine maxCpus="255">pc-i440fx-5.0</machine>
      <machine maxCpus="255">pc-i440fx-2.8</machine>
      <machine maxCpus="255">pc-i440fx-eoan</machine>
      <machine maxCpus="255">pc-q35-2.5</machine>
      <machine maxCpus="255">pc-i440fx-3.0</machine>
      <machine maxCpus="255">pc-q35-yakkety</machine>
      <machine maxCpus="288">pc-q35-2.11</machine>
      <domain type="qemu"/>
      <domain type="kvm"/>
    </arch>
    <features>
      <acpi default="on" toggle="yes"/>
      <apic default="on" toggle="no"/>
      <cpuselection/>
      <deviceboot/>
      <disksnapshot default="on" toggle="no"/>
    </features>
  </guest>
 
</capabilities>
 
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:739) Using domain events
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:777) Using network events
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:796) Using storage pool events
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:821) Using node device events
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:691) storage pool refresh event: pool=iso-store
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:1076) network=default status=Active added
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:1076) domain=win10gaming status=Shutoff added
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:691) storage pool refresh event: pool=nvram
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:691) storage pool refresh event: pool=default
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:1076) pool=iso-store status=Active added
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:1076) pool=nvram status=Active added
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:1076) pool=default status=Active added
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (storage:139) Found default pool name=default target=/var/lib/libvirt/images
[Thu, 18 Nov 2021 15:51:47 virt-manager 43336] DEBUG (connection:482) conn=qemu:///system changed to state=Active
[Thu, 18 Nov 2021 15:51:48 virt-manager 43336] DEBUG (serialcon:17) Using VTE API 2.91
[Thu, 18 Nov 2021 15:51:48 virt-manager 43336] DEBUG (xmleditor:12) Using GtkSource 4
[Thu, 18 Nov 2021 15:51:48 virt-manager 43336] DEBUG (nodedev:240) Error parsing node device string.
Traceback (most recent call last):
  File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 238, in _AddressStringToHostdev
    raise RuntimeError("Unknown address type")
RuntimeError: Unknown address type
[Thu, 18 Nov 2021 15:51:48 virt-manager 43336] DEBUG (nodedev:81) Error looking up nodedev from idstring=pci_0000_09_00_0
Traceback (most recent call last):
  File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 79, in lookupNodedevFromString
    return _AddressStringToNodedev(conn, idstring)
  File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 247, in _AddressStringToNodedev
    hostdev = _AddressStringToHostdev(conn, addrstr)
  File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 238, in _AddressStringToHostdev
    raise RuntimeError("Unknown address type")
RuntimeError: Unknown address type
[Thu, 18 Nov 2021 15:51:48 virt-manager 43336] DEBUG (error:101) error dialog message:
summary=Error launching details: Unknown address type
details=Traceback (most recent call last):
  File "/home/toby/Workspace/virt-manager/./virtManager/vmwindow.py", line 40, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "/home/toby/Workspace/virt-manager/./virtManager/vmwindow.py", line 82, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
  File "/home/toby/Workspace/virt-manager/./virtManager/details/details.py", line 377, in __init__
    self.gfxdetails = vmmGraphicsDetails(
  File "/home/toby/Workspace/virt-manager/./virtManager/device/gfxdetails.py", line 56, in __init__
    self._init_ui()
  File "/home/toby/Workspace/virt-manager/./virtManager/device/gfxdetails.py", line 118, in _init_ui
    model.append([rendernode, i.pretty_name()])
  File "/home/toby/Workspace/virt-manager/./virtManager/object/nodedev.py", line 62, in pretty_name
    return _pretty_name(self.xmlobj)
  File "/home/toby/Workspace/virt-manager/./virtManager/object/nodedev.py", line 38, in _pretty_name
    parent = NodeDevice.lookupNodedevFromString(
  File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 79, in lookupNodedevFromString
    return _AddressStringToNodedev(conn, idstring)
  File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 247, in _AddressStringToNodedev
    hostdev = _AddressStringToHostdev(conn, addrstr)
  File "/home/toby/Workspace/virt-manager/./virtinst/nodedev.py", line 238, in _AddressStringToHostdev
    raise RuntimeError("Unknown address type")
RuntimeError: Unknown address type
[Thu, 18 Nov 2021 15:51:48 virt-manager 43336] DEBUG (cli:195) Uncaught exception:
Traceback (most recent call last):
  File "/home/toby/Workspace/virt-manager/./virtManager/manager.py", line 473, in show_vm
    vmmenu.VMActionUI.show(self, self.current_vm())
  File "/home/toby/Workspace/virt-manager/./virtManager/vmmenu.py", line 324, in show
    vmmVMWindow.get_instance(src, vm).show()
AttributeError: 'NoneType' object has no attribute 'show'
 
[Thu, 18 Nov 2021 15:51:57 virt-manager 43336] DEBUG (manager:196) Closing manager
[Thu, 18 Nov 2021 15:51:57 virt-manager 43336] DEBUG (engine:323) window counter decremented to 0
[Thu, 18 Nov 2021 15:51:57 virt-manager 43336] DEBUG (engine:343) No windows found, requesting app exit
[Thu, 18 Nov 2021 15:51:57 virt-manager 43336] DEBUG (connection:837) conn.close() uri=qemu:///system
[Thu, 18 Nov 2021 15:51:57 virt-manager 43336] ERROR (baseclass:98) Error cleaning up <vmwindow.vmmVMWindow object at 0x7f84cc19ce80 (virtManager+vmwindow+vmmVMWindow at 0x13a5e60)>
Traceback (most recent call last):
  File "/home/toby/Workspace/virt-manager/./virtManager/baseclass.py", line 88, in cleanup
    self._cleanup()
  File "/home/toby/Workspace/virt-manager/./virtManager/vmwindow.py", line 170, in _cleanup
    self._details.cleanup()
AttributeError: 'vmmVMWindow' object has no attribute '_details'
[Thu, 18 Nov 2021 15:51:57 virt-manager 43336] DEBUG (connection:482) conn=qemu:///system changed to state=Disconnected
[Thu, 18 Nov 2021 15:51:57 virt-manager 43336] DEBUG (engine:369) Exiting app normally.
  ```
</details>

**Comment by crobinso** [comment]
Thanks for the report. Something strange is happening here indeed. I'll investigate

**Comment by crobinso** [comment]
So our code here needs some improvement. The error message in git is a bit less opaque but there's more to do. But yeah I'm also confused what is wrong here. I think your libvirt is showing us a 'drm' nodedev, and the parent field is pointing to a nodedev device name that doesn't exist, and our code isn't expecting that to happen.

@Toby4213 https://github.com/Toby4213Can you pastebin/gist the output of: `for i in $(sudo virsh nodedev-list --all); do sudo virsh nodedev-dumpxml $i; done`

**Comment by Toby4213** [comment]
Sorry, I have already deleted that vm config, just kept the disk and recreated the config. I tried to recreate the problem by cloning the VM again, but the error didn't occur this time. If it happens again I will run that command and post the output.

**Comment by crobinso** [comment]
Okay thanks. I think I fixed the error in git but still not sure why libvirt output would have hit the original issue.
