### ISSUE TITLE
cant make a new vm 

### ISSUE THREAD

**Issue by jsxxxashadha** [virt-manager/virt-manager#333]
hello whenever i create a new virtual machine it and i press the finish button i get this error Unable to complete install: 'Unable to set XATTR trusted.libvirt.security.dac on /var/lib/libvirt/qemu/domain-4-win10/master-key.aes: Operation not permitted'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2001, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 701, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 649, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4366, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: Unable to set XATTR trusted.libvirt.security.dac on /var/lib/libvirt/qemu/domain-4-win10/master-key.aes: Operation not permitted
 i was wondering if you know the fix

**Comment by crobinso** [comment]
I don't know what is causing the root issue exactly, but you can skip this by disabling `remember_owner` in `/etc/libvirt/qemu.conf`

**Comment by Me98pixel** [comment]
how do i disable remember_owner in /etc/libvirt/qemu.conf (im using debian)

**Comment by DarkevilPT** [comment]
> how do i disable remember_owner in /etc/libvirt/qemu.conf (im using debian)

echo "remember_owner = 0" | sudo tee -a /etc/libvirt/qemu.conf 
sudo systemctl restart libvirtd
