### ISSUE TITLE
virt-xml requires connecting to libvirt even when operating as a filter

### ISSUE THREAD

**Issue by andreabolognani** [virt-manager/virt-manager#344]
I'm trying to use virt-xml as a filter to modify an existing domain XML, but doing so fails unless the tool can connect to libvirt:

```
$ virt-xml --print-xml --edit all --disk iotune.total_bytes_sec=52428800,iotune.total_iops_sec=1000 <in.xml >out.xml
ERROR    Operation not supported: Cannot use direct socket mode if no URI is set
```

I've hacked the code as follows just to see how badly it would break:

```diff
diff --git a/virtinst/virtxml.py b/virtinst/virtxml.py
index d06320f6..b11e9281 100644
--- a/virtinst/virtxml.py
+++ b/virtinst/virtxml.py
@@ -492,7 +492,7 @@ def main(conn=None):
         fail(_("Don't know how to --update for --%s") %
              (parserclass.cli_arg_name))
 
-    conn = cli.getConnection(options.connect, conn)
+    #conn = cli.getConnection(options.connect, conn)
 
     domain = None
     active_xmlobj = None
```

Much to my surprise, the original invocation now succeeds and produces the expected results. Another simple invocation still fail though: 

```
$ virt-xml --debug --print-xml --add-device --disk /var/lib/libvirt/images/test.qcow2,format=qcow2 <in.xml >out.xml
[Thu, 23 Dec 2021 09:28:16 virt-xml 339] DEBUG (cli:204) Launched with command line: /usr/bin/virt-xml --debug --print-xml --add-device --disk /var/lib/libvirt/images/test.qcow2,format=qcow2
[Thu, 23 Dec 2021 09:28:16 virt-xml 339] DEBUG (cli:1516) Exception parsing inst=<DeviceDisk disk 139894888781568> optstr=/var/lib/libvirt/images/test.qcow2,format=qcow2
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtinst/cli.py", line 1503, in parse
    objs = self._parse(inst is None and self.guest or inst)
  File "/usr/share/virt-manager/virtinst/cli.py", line 3311, in _parse
    super()._parse(inst)
  File "/usr/share/virt-manager/virtinst/cli.py", line 1473, in _parse
    param.parse_param(self, inst)
  File "/usr/share/virt-manager/virtinst/cli.py", line 1135, in parse_param
    self._virtarg.cb(parser, inst, self.val, self)
  File "/usr/share/virt-manager/virtinst/cli.py", line 3361, in set_path_cb
    inst.set_source_path(val)
  File "/usr/share/virt-manager/virtinst/devices/disk.py", line 640, in set_source_path
    (vol_object, parent_pool) = diskbackend.manage_path(self.conn, newpath)
  File "/usr/share/virt-manager/virtinst/diskbackend.py", line 143, in manage_path
    if not conn.support.conn_storage():
AttributeError: 'NoneType' object has no attribute 'support'
[Thu, 23 Dec 2021 09:28:16 virt-xml 339] DEBUG (cli:255)   File "/usr/bin/virt-xml", line 8, in <module>
    virtxml.runcli()
  File "/usr/share/virt-manager/virtinst/virtxml.py", line 556, in runcli
    sys.exit(main())
  File "/usr/share/virt-manager/virtinst/virtxml.py", line 520, in main
    devs, action = prepare_changes(inactive_xmlobj, options, parserclass)
  File "/usr/share/virt-manager/virtinst/virtxml.py", line 326, in prepare_changes
    devs = action_add_device(xmlobj, options, parserclass)
  File "/usr/share/virt-manager/virtinst/virtxml.py", line 167, in action_add_device
    devs = cli.parse_option_strings(options, guest, None)
  File "/usr/share/virt-manager/virtinst/cli.py", line 4401, in parse_option_strings
    parseret = parserobj.parse(inst)
  File "/usr/share/virt-manager/virtinst/cli.py", line 1518, in parse
    fail(_("Error: %(cli_flag_name)s %(options)s: %(err)s") %
  File "/usr/share/virt-manager/virtinst/cli.py", line 255, in fail
    log.debug("".join(traceback.format_stack()))

[Thu, 23 Dec 2021 09:28:16 virt-xml 339] ERROR (cli:256) Error: --disk /var/lib/libvirt/images/test.qcow2,format=qcow2: 'NoneType' object has no attribute 'support'
[Thu, 23 Dec 2021 09:28:16 virt-xml 339] DEBUG (cli:258) 
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtinst/cli.py", line 1503, in parse
    objs = self._parse(inst is None and self.guest or inst)
  File "/usr/share/virt-manager/virtinst/cli.py", line 3311, in _parse
    super()._parse(inst)
  File "/usr/share/virt-manager/virtinst/cli.py", line 1473, in _parse
    param.parse_param(self, inst)
  File "/usr/share/virt-manager/virtinst/cli.py", line 1135, in parse_param
    self._virtarg.cb(parser, inst, self.val, self)
  File "/usr/share/virt-manager/virtinst/cli.py", line 3361, in set_path_cb
    inst.set_source_path(val)
  File "/usr/share/virt-manager/virtinst/devices/disk.py", line 640, in set_source_path
    (vol_object, parent_pool) = diskbackend.manage_path(self.conn, newpath)
  File "/usr/share/virt-manager/virtinst/diskbackend.py", line 143, in manage_path
    if not conn.support.conn_storage():
AttributeError: 'NoneType' object has no attribute 'support'
```

I didn't dig into this further, but I wonder: do you think making virt-xml usable as a filter without requiring a connection to libvirt is something that could actually be achieved if enough effort were to be put into it, or is use of the connection far too ingrained to be made optional at this point?

**Comment by crobinso** [comment]
Interesting. For some things that are just basic XML edits, yeah a connection isn't required. It would be for adding devices though, since we check the conn to fill in defaults, which are often driver specific or require domcapabilities. Code wise though, it would be pretty invasive or hacky to try to make this work, and error nicely when we hit code where conn is required. If you want to try it in kubevirt, using `--connect test:///default` will probably get you pretty far
