### ISSUE TITLE
"programming error: Did not find widget name=fs-mode-combo"

### ISSUE THREAD

**Issue by harvey-git** [virt-manager/virt-manager#371]
**Distro**: Ubuntu 22.04
When I upgraded ubuntu 20.04 to 22.04, vir-manager was also upgraded from 2.2 to 3.2, and then the following error was reported and it could not run normally.
![image](https://user-images.githubusercontent.com/52305566/158045371-0d023ba2-a76e-4c06-8bd6-5a59d7ef92a9.png)
`programming error: Did not find widget name=fs-mode-combo

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 40, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 82, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
  File "/usr/share/virt-manager/virtManager/details/details.py", line 373, in __init__
    self.gfxdetails.connect("changed", _e(EDIT_GFX))
  File "/usr/share/virt-manager/virtManager/device/fsdetails.py", line 62, in __init__
    self.top_box = self.widget("vmm-fs-details")
  File "/usr/share/virt-manager/virtManager/device/fsdetails.py", line 102, in _init_ui
    simple_store_set("fs-driver-combo",
  File "/usr/share/virt-manager/virtManager/device/fsdetails.py", line 80, in simple_store_set
    # [XML value, label]
  File "/usr/share/virt-manager/virtManager/baseclass.py", line 311, in widget
    raise xmlutil.DevError("Did not find widget name=%s" % name)
virtinst.xmlutil.DevError: programming error: Did not find widget name=fs-mode-combo`

**Comment by crobinso** [comment]
Since you are getting your package from distro repos, you need to file a bug with your distro. virt-manager is at release 4.0.0 upstream.

You may want  try fully uninstalling virt-manager, then reinstalling it. You system could be in some kind of inconsistent state
