### ISSUE TITLE
Cannot rename virtual machine

### ISSUE THREAD

**Issue by Frontlemon** [virt-manager/virt-manager#372]
**Distro**: Arch Linux
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.16.14-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3720QM CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

If I try to rename an existing virtual machine, I get the following error:

Error applying changes: expected str, bytes or os.PathLike object, not NoneType

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/details/details.py", line 1320, in _config_apply
    success = self._apply_overview()
  File "/usr/share/virt-manager/virtManager/details/details.py", line 1414, in _apply_overview
    self.vm.rename_domain(self.widget("overview-name").get_text())
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 570, in rename_domain
    new_nvram, old_nvram = self._copy_nvram_file(new_name)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 547, in _copy_nvram_file
    nvram_dir = os.path.dirname(old_nvram.get_source_path())
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by coreyberla** [comment]
What's the original and desired names?

**Comment by Frontlemon** [comment]
The original name was:
win10
I want to change it to say:
windows10
Note that I **do not** put spaces or other special characters in the name.

**Comment by crobinso** [comment]
Thanks for the report, I've fixed this upstream now.

**Comment by tsc-targitaj** [comment]
Got it too ((
