### ISSUE TITLE
Cannot create new VM with Version4.00

### ISSUE THREAD

**Issue by grisu280871** [virt-manager/virt-manager#373]
Hi, with new version of Virt-Manager 4.00 I cannot create new VM's anymore.

For example, when I try to boot the current Arch-ISO I get the following error:

Installation konnte nicht fertiggestellt werden: «Interner Fehler: process exited while connecting to monitor: 2022-03-20T15:43:33.651586Z qemu-system-x86_64: -blockdev {"driver":"file","filename":"/home/peter/Downloads/archlinux-2022.03.01-x86_64.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/home/peter/Downloads/archlinux-2022.03.01-x86_64.iso': Permission denied»

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
  File "/usr/lib/python3.10/site-packages/libvirt.py", line 4400, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: Interner Fehler: process exited while connecting to monitor: 2022-03-20T15:43:33.651586Z qemu-system-x86_64: -blockdev {"driver":"file","filename":"/home/peter/Downloads/archlinux-2022.03.01-x86_64.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/home/peter/Downloads/archlinux-2022.03.01-x86_64.iso': Permission denied

**Comment by crobinso** [comment]
Thanks for the report. Is this actually specific to virt-manager 4.0.0? Can you try downgrading to the previous version and see if the behavior is different? From the error message my guess is this isn't virt-manager's doing, seems like a more generic permissions issue.
