### ISSUE TITLE
ValueError: Namespace Libosinfo not available

### ISSUE THREAD

**Issue by Retterath** [virt-manager/virt-manager#380]
**Distro**: 

Hi,

im trying to install virt-manager via github and not with sudo apt-get _etc_. I ran the **setup.py install** and no error appeared in the terminal. After i tried the `virt-install --help` i received
`Traceback (most recent call last):
  File "/home/virt/Desktop/Project/FT_master-slave/data/bash/virt-manager/virt-install", line 8, in <module>
    from virtinst import virtinstall
  File "/home/virt/Desktop/Project/FT_master-slave/data/bash/virt-manager/virtinst/__init__.py", line 9, in <module>
    gi.require_version('Libosinfo', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Libosinfo not available`
despite the fact that i have installed libosinfo-1.0.0 with version 1.7.1-1
The things ive tried so far:
`sudo apt-get upgrade -y
apt-cache policy libosinfo-1.0-0` (_to check if the correct version is installed_)

Also, i have already installed the following dependencies:
_bridge-utils >= 1.6-2ubuntu1
ibus-gtk3 >= 1.5.22-2ubuntu2.1
libcanberra-gtk3-0 >= 0.30-7ubuntu1
libcanberra-gtk3-module >= 0.30-7ubuntu1 
libdbusmenu-gtk3-4 >= 16.04.1+18.10.20180917-0ubuntu6
libgtk3-perl >= 0.037-1
python3-aptdaemon.gtk3widgets >= 1.1.1+bzr982-0ubuntu32.3
gettext >= 0.19.8.1-10build1
gettext-base >= 0.19.8.1-10build1
libosinfo-1.0-0 >= 1.7.1-1
libgtksourceview-4-common >= 4.6.0-1
qemu >= 1:4.2-3ubuntu6.21
qemu-utils >= 1:4.2-3ubuntu6.21
qemu-kvm >= 1:4.2-3ubuntu6.21
qemu-block-extra >= 1:4.2-3ubuntu6.21
qemu-system-common >= 1:4.2-3ubuntu6.21
qemu-system-data >= 1:4.2-3ubuntu6.21
qemu-system-gui >= 1:4.2-3ubuntu6.21
qemu-system-x86 >= 1:4.2-3ubuntu6.21
python3 >= 3.8.2-0ubuntu2
python3-libvirt >= 6.1.0-1
libvirt0 >= 6.0.0-0ubuntu8.15
libvirt-clients >= 6.0.0-0ubuntu8.15
libvirt-daemon >= 6.0.0-0ubuntu8.15
libvirt-daemon-system >= 6.0.0-0ubuntu8.15
libvirt-daemon-system-systemd >= 6.0.0-0ubuntu8.15
libvirt-daemon-driver-qemu >= 6.0.0-0ubuntu8.15
libvirt-daemon-driver-storage-rbd >= 6.0.0-0ubuntu8.15_

**Comment by crobinso** [comment]
See INSTALL.md, there's a note about this. I think the package you need is gir1.2-libosinfo-1.0

**Comment by elliotmtx** [comment]
@crobinso where can I get source code for gir1.2-libosinfo-1.0?
