### ISSUE TITLE
PCI bus error, and after that it complains about deprecated booleans.

### ISSUE THREAD

**Issue by Sasytoremember** [virt-manager/virt-manager#424]
Debian 11
5.10 kernel
x86_64
version 4.10 virt-manager Compiled from source, also happens with distro-binary
Emulating cpu: m68k, model: virt 7.1
qemu version: QEMU emulator version 7.0.91 (v7.1.0-rc1-14-g09ed077d7f)

The issue is that it complains about PCI buses not being available,
"Unable to complete install: 'XML error: No PCI buses available"
```
Traceback (most recent call last):
  File "/home/user/virt-manager/./virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/home/user/virt-manager/./virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/home/user/virt-manager/./virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
  File "/home/user/virt-manager/./virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4366, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: XML error: No PCI buses available
```
And when I add a PCI bus manually, it complains about a lot of booleans being deprecated.
(Here's what i added: ```<controller type="pci" model="pci-root"/>``` i tried again with ```<controller type="pci" index="0" model="pci-root"/>``` )
```
Unable to complete install: 'internal error: qemu unexpectedly closed the monitor: qemu-system-m68k: -chardev socket,id=charmonitor,fd=34,server,nowait: warning: short-form boolean option 'server' deprecated
Please use server=on instead
qemu-system-m68k: -chardev socket,id=charmonitor,fd=34,server,nowait: warning: short-form boolean option 'nowait' deprecated
Please use wait=off instead
2022-08-08T00:57:04.679234Z qemu-system-m68k: -device virtio-blk-pci,bus=pci,addr=0x3,drive=libvirt-1-format,id=virtio-disk0,bootindex=1: 'virtio-blk-pci' is not a valid device model name'

Traceback (most recent call last):
  File "/home/user/virt-manager/./virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/home/user/virt-manager/./virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/home/user/virt-manager/./virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
  File "/home/user/virt-manager/./virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4366, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: qemu-system-m68k: -chardev socket,id=charmonitor,fd=34,server,nowait: warning: short-form boolean option 'server' deprecated
Please use server=on instead
qemu-system-m68k: -chardev socket,id=charmonitor,fd=34,server,nowait: warning: short-form boolean option 'nowait' deprecated
Please use wait=off instead
2022-08-08T00:57:04.679234Z qemu-system-m68k: -device virtio-blk-pci,bus=pci,addr=0x3,drive=libvirt-1-format,id=virtio-disk0,bootindex=1: 'virtio-blk-pci' is not a valid device model name
```
and here's my xml configuration:
```
<domain type="qemu">
  <name>debian10-m68k</name>
  <uuid>5819fd38-76b1-49ee-afe8-73befc9d8cd5</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://debian.org/debian/10"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory>1048576</memory>
  <currentMemory>1048576</currentMemory>
  <vcpu current="1">1</vcpu>
  <os>
    <type arch="m68k" machine="virt-7.1">hvm</type>
    <boot dev="hd"/>
  </os>
  <clock offset="utc"/>
  <devices>
    <emulator>/usr/bin/qemu-system-m68k</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="/home/user/Downloads/debian-10.0.qcow2"/>
      <target dev="sda" bus="scsi"/>
    </disk>
    <interface type="network">
      <source network="default"/>
      <mac address="52:54:00:13:9f:d3"/>
      <model type="virtio"/>
    </interface>
    <controller type="pci" model="pci-root"/>
  </devices>
</domain>
```

**Comment by crobinso** [comment]
Thanks for the report. I haven't looked at this closely but I'm guessing libvirt needs work to support arch `m68k`. For example there isn't a single unit test case in libvirt for m68k XML, which typically means a developer has never confirmed it works.

If you can get some XML config working outside of virt-manager, then we can revisit what we need to do in virt-manager/virt-install to make that case work out of the box. But until there's working XML this is likely a libvirt problem, so I'm closing this
