### ISSUE TITLE
Using the storage view triggers attributeError: type object 'vmmStoragePool' has no attribute 'pretty_type'

### ISSUE THREAD

**Issue by cpaelzer** [virt-manager/virt-manager#47]
Hi,
with 2.2.1 I get this traceback:
```
[Di, 20 Aug 2019 11:09:52 virt-manager 15468] DEBUG (cli:197) Uncaught exception:
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/createvm.py", line 1198, in _browse_iso
    self._browse_file(None, cb=set_path, is_media=True)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 1304, in _browse_file
    self._storage_browser = vmmStorageBrowser(self.conn)
  File "/usr/share/virt-manager/virtManager/storagebrowse.py", line 26, in __init__
    self._vol_sensitive_cb)
  File "/usr/share/virt-manager/virtManager/hoststorage.py", line 107, in __init__
    self._populate_pools()
  File "/usr/share/virt-manager/virtManager/hoststorage.py", line 388, in _populate_pools
    typ = vmmStoragePool.pretty_type(pool.get_type())
AttributeError: type object 'vmmStoragePool' has no attribute 'pretty_type'
```

I wondered if the file is missing or anything like it, but things are in place:
```
$ grep -C 4 pretty_type /usr/share/virt-manager/virtManager/object/storagepool.py
            ])
        return pool_type in supported

    @staticmethod
    def pretty_type(pool_type):
        return POOL_TYPE_DESCS.get(pool_type, "%s pool" % pool_type)

    @staticmethod
    def list_types():

```

This is probably related to commit 4a0b7f61c88ba523b1376325e3bb2f47429849ad which is new in 2.2.1.

**Comment by cpaelzer** [comment]
I beg your pardon, it seems that it had the program still up in background and effectively ran some sources from 2.2.0 and some from 2.2.1.
While I don't yet understand entirely what happened (would be worth to ensure it isn't happening to anyone else) it is resolved for now and not really an issue in the code.
