### ISSUE TITLE
--extra-args doesn't work with --location pointing to Fedora 37 ISO

### ISSUE THREAD

**Issue by andreabolognani** [virt-manager/virt-manager#480]
**Short version**

`virt-install --location fedora36.iso --extra-args console=ttyS0` works and behaves as expected, presenting the installer on the serial console. The exact same command line stops working when using a Fedora 37 ISO as the installation source.

**Longer version**

In order to implement `--extra-args` in this scenario, virt-install needs to extract the kernel and initrd from the ISO, save them to a temporary location, and configure the VM to perform direct kernel boot via an XML snippet along the lines of

```xml
<os> 
  <type arch="x86_64" machine="q35">hvm</type>
  <kernel>/var/lib/libvirt/boot/virtinst-ll_lrc8f-vmlinuz</kernel>
  <initrd>/var/lib/libvirt/boot/virtinst-x0ig7vph-initrd.img</initrd>
  <cmdline>console=ttyS0</cmdline>
</os>
```

The paths where it expects to find the kernel and initrd inside the ISO are `isolinux/vmlinuz` and `isolinux/initrd.img` respectively.

However, as a consequence of the [BIOSBootISOWithGrub2](https://fedoraproject.org/wiki/Changes/BIOSBootISOWithGrub2) change included in Fedora 37, those files no longer exist in the ISO and virt-install fails.

I have no idea whether it's possible to make `--extra-args` work with the new GRUB-based implementation. If not, virt-install should at the very least produce a nice error message informing the user of the situation.

Note that `/images/pxeboot/vmlinuz` and `/images/pxeboot/initrd.img`, which virt-install will use for network booting, seem to also be used for EFI: `/EFI/BOOT/BOOT.conf` contains

```
menuentry 'Install Fedora 37' --class fedora --class gnu-linux --class gnu --class os {
  linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=Fedora-S-dvd-x86_64-37 quiet
  initrdefi /images/pxeboot/initrd.img
}
``` 

and in fact using `--location fedora37.iso,kernel=/images/pxeboot/vmlinuz,initrd=/images/pxeboot/initrd.img` instead of just `--location fedora37.iso` seems to be an effective workaround for the issue. Perhaps virt-install could just fall back to those files if the ones in the top-level directory of the ISO don't exist?

**Detailed output**

For Fedora 36 ISO:

```
[Mon, 16 Jan 2023 15:28:08 virt-install 23954] DEBUG (cli:204) Version 4.1.0 launched with command line: ./virt-install --debug --name iso36 --location /home/abologna/Downloads/Fedora-Server-dvd-x86_64-36-1.5.iso --virt-type kvm --ram 4096 --vcpus 4 --graphics none --disk size=5 --network default --extra-args console=ttyS0 --wait 0
[ ... ]
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (disk:239) DeviceDisk.check_path_search path=/home/abologna/Downloads/Fedora-Server-dvd-x86_64-36-1.5.iso
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (cli:266) 
Starting install...
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (urlfetcher:34) Generating iso filelist: ['xorriso', '-indev', '/home/abologna/Downloads/Fedora-Server-dvd-x86_64-36-1.5.iso', '-print', 'VIRTINST_BEGINLIST', '-find']
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (urlfetcher:174) hasFile(/isolinux/vmlinuz) returning True
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (urlfetcher:174) hasFile(/isolinux/initrd.img) returning True
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (urlfetcher:46) Extracting iso file: ['xorriso', '-osirrox', 'on', '-indev', '/home/abologna/Downloads/Fedora-Server-dvd-x86_64-36-1.5.iso', '-extract', '/isolinux/vmlinuz', '/home/abologna/.cache/virt-manager/boot/virtinst-isogbtc3c7b-vmlinuz']
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (urlfetcher:105) Fetching URI: /isolinux/vmlinuz

Starting install...

Retrieving 'vmlinuz'                                        |  11 MB  00:00     
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (urlfetcher:190) Saved file to /home/abologna/.cache/virt-manager/boot/virtinst-ll_lrc8f-vmlinuz
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (urlfetcher:46) Extracting iso file: ['xorriso', '-osirrox', 'on', '-indev', '/home/abologna/Downloads/Fedora-Server-dvd-x86_64-36-1.5.iso', '-extract', '/isolinux/initrd.img', '/home/abologna/.cache/virt-manager/boot/virtinst-isoiwv0bgql-initrd.img']
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (urlfetcher:105) Fetching URI: /isolinux/initrd.img

Retrieving 'initrd.img'                                     |  96 MB  00:00     
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (urlfetcher:190) Saved file to /home/abologna/.cache/virt-manager/boot/virtinst-x0ig7vph-initrd.img
[Mon, 16 Jan 2023 15:28:09 virt-install 23954] DEBUG (volumeupload:136) Uploading kernel/initrd media
[ ... ]
```

For Fedora 37 ISO:

```
[Mon, 16 Jan 2023 15:28:29 virt-install 24081] DEBUG (cli:204) Version 4.1.0 launched with command line: ./virt-install --debug --name iso37 --location /home/abologna/Downloads/Fedora-Server-dvd-x86_64-37-1.7.iso --virt-type kvm --ram 4096 --vcpus 4 --graphics none --disk size=5 --network default --extra-args console=ttyS0 --wait 0
[ ... ]
[Mon, 16 Jan 2023 15:28:29 virt-install 24081] DEBUG (disk:239) DeviceDisk.check_path_search path=/home/abologna/Downloads/Fedora-Server-dvd-x86_64-37-1.7.iso
[Mon, 16 Jan 2023 15:28:29 virt-install 24081] DEBUG (cli:266) 
Starting install...
[Mon, 16 Jan 2023 15:28:29 virt-install 24081] DEBUG (urlfetcher:34) Generating iso filelist: ['xorriso', '-indev', '/home/abologna/Downloads/Fedora-Server-dvd-x86_64-37-1.7.iso', '-print', 'VIRTINST_BEGINLIST', '-find']
[Mon, 16 Jan 2023 15:28:29 virt-install 24081] DEBUG (urlfetcher:174) hasFile(/isolinux/vmlinuz) returning False
[Mon, 16 Jan 2023 15:28:29 virt-install 24081] DEBUG (cli:256)   File "/home/abologna/src/upstream/virt-manager/./virt-install", line 9, in <module>
    virtinstall.runcli()
  File "/home/abologna/src/upstream/virt-manager/./virtinst/virtinstall.py", line 1241, in runcli
    sys.exit(main())
  File "/home/abologna/src/upstream/virt-manager/./virtinst/virtinstall.py", line 1234, in main
    start_install(guest, installer, options)
  File "/home/abologna/src/upstream/virt-manager/./virtinst/virtinstall.py", line 982, in start_install
    fail(e, do_exit=False)
  File "/home/abologna/src/upstream/virt-manager/./virtinst/cli.py", line 256, in fail
    log.debug("".join(traceback.format_stack()))

[Mon, 16 Jan 2023 15:28:29 virt-install 24081] ERROR (cli:257) Couldn't find kernel for install tree.
[Mon, 16 Jan 2023 15:28:29 virt-install 24081] DEBUG (cli:259) 
Traceback (most recent call last):
  File "/home/abologna/src/upstream/virt-manager/./virtinst/virtinstall.py", line 962, in start_install
    domain = installer.start_install(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abologna/src/upstream/virt-manager/./virtinst/install/installer.py", line 685, in start_install
    self._prepare(guest, meter)
  File "/home/abologna/src/upstream/virt-manager/./virtinst/install/installer.py", line 391, in _prepare
    self._prepare_treemedia(guest, meter, unattended_scripts)
  File "/home/abologna/src/upstream/virt-manager/./virtinst/install/installer.py", line 364, in _prepare_treemedia
    kernel, initrd, kernel_args = self._treemedia.prepare(guest, meter,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abologna/src/upstream/virt-manager/./virtinst/install/installertreemedia.py", line 279, in prepare
    kernel, initrd = self._prepare_kernel_url(guest, cache, fetcher)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abologna/src/upstream/virt-manager/./virtinst/install/installertreemedia.py", line 211, in _prepare_kernel_url
    kernelpath, initrdpath = _check_kernel_pairs()
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/abologna/src/upstream/virt-manager/./virtinst/install/installertreemedia.py", line 208, in _check_kernel_pairs
    raise RuntimeError(  # pragma: no cover
RuntimeError: Couldn't find kernel for install tree.
```

**Comment by crobinso** [comment]
I believe this was temporary breakage: f37 iso lost treeinfo, but that was fixed. And osinfo-db was eventually updated to also point to new kernel and initrd locations. I just tried your command with f40 server netinst iso, and saw serial output in `virsh console`, so I think we are all good.

**Comment by andreabolognani** [comment]
I can confirm your results, and in fact even the more recent F37 ISO (`Fedora-Server-netinst-x86_64-37-1.7.iso`) seems to work fine. So they probably caught the issue and started producing fixed images. Good!
