### ISSUE TITLE
KVM did not launch

### ISSUE THREAD

**Issue by Frankimuni** [virt-manager/virt-manager#522]
**Distro**: 

Error launching details: Host does not support domain type kvm with machine 'pc-q35-7.0' for virtualization type 'hvm' with architecture 'x86_64'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 40, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
                          ^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 83, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/details/details.py", line 389, in __init__
    self._init_details()
  File "/usr/share/virt-manager/virtManager/details/details.py", line 807, in _init_details
    vmmAddHardware.build_video_combo(self.vm, video_dev)
  File "/usr/share/virt-manager/virtManager/addhardware.py", line 816, in build_video_combo
    default = DeviceVideo.default_model(vm.xmlobj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/devices/video.py", line 47, in default_model
    if (guest.lookup_domcaps().supports_video_virtio() and
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/guest.py", line 656, in lookup_domcaps
    if not self._domcaps or not _compare(self._domcaps):
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/guest.py", line 646, in _compare
    if self.os.machine and not _compare_machine(domcaps):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/guest.py", line 633, in _compare_machine
    capsinfo = self.lookup_capsinfo()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/guest.py", line 674, in lookup_capsinfo
    self._capsinfo = self.conn.caps.guest_lookup(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/capabilities.py", line 319, in guest_lookup
    raise ValueError(msg)
ValueError: Host does not support domain type kvm with machine 'pc-q35-7.0' for virtualization type 'hvm' with architecture 'x86_64'

**Comment by Frankimuni** [comment]
Here is the error report:

Error launching details: Host does not support domain type kvm with machine 'pc-q35-7.0' for virtualization type 'hvm' with architecture 'x86_64'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 40, in get_instance
    cls._instances[key] = vmmVMWindow(vm)
                          ^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/vmwindow.py", line 83, in __init__
    self._details = vmmDetails(self.vm, self.builder, self.topwin,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/details/details.py", line 389, in __init__
    self._init_details()
  File "/usr/share/virt-manager/virtManager/details/details.py", line 807, in _init_details
    vmmAddHardware.build_video_combo(self.vm, video_dev)
  File "/usr/share/virt-manager/virtManager/addhardware.py", line 816, in build_video_combo
    default = DeviceVideo.default_model(vm.xmlobj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/devices/video.py", line 47, in default_model
    if (guest.lookup_domcaps().supports_video_virtio() and
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/guest.py", line 656, in lookup_domcaps
    if not self._domcaps or not _compare(self._domcaps):
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/guest.py", line 646, in _compare
    if self.os.machine and not _compare_machine(domcaps):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/guest.py", line 633, in _compare_machine
    capsinfo = self.lookup_capsinfo()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/guest.py", line 674, in lookup_capsinfo
    self._capsinfo = self.conn.caps.guest_lookup(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/capabilities.py", line 319, in guest_lookup
    raise ValueError(msg)
ValueError: Host does not support domain type kvm with machine 'pc-q35-7.0' for virtualization type 'hvm' with architecture 'x86_64'

**Comment by crobinso** [comment]
Thanks for the report. This usually happens if you created a VM with a new libvirt/qemu version, and then downgraded qemu. This isn't anything virt-manager can fix for you really. Do `sudo virsh edit $VMNAME` and replace `pc-q35-7.0` with just `pc` and itll probably work. Or re-upgrade to the newer qemu

**Comment by crobinso** [comment]
> Small correction, `pc` will be translated to `pc-i440fx-...` and will produce error message, the correct machine type you want to use to fix such VM is `q35`.

Argh good catch. I'll edit my comment
