### ISSUE TITLE
Error shutting down domain: Requested operation is not valid: domain is not running

### ISSUE THREAD

**Issue by sanalvv** [virt-manager/virt-manager#527]
rror shutting down domain: Requested operation is not valid: domain is not running

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1357, in shutdown
    self._backend.shutdown()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 2923, in shutdown
    raise libvirtError('virDomainShutdown() failed')
libvirt.libvirtError: Requested operation is not valid: domain is not running

**Comment by crobinso** [comment]
I'm guessing this was transient libvirt or qemu breakage. If you are still reproducing, please file a new issue and provide all the information requested in the issue template.
