### ISSUE TITLE
Error refreshing hardware page: 'virConnect' object has no attribute 'baselineHypervisorCPU'

### ISSUE THREAD

**Issue by bojansimicmb** [virt-manager/virt-manager#57]
When going to Show virutal hardware details>CPUs constantly getting this error.

Error refreshing hardware page: 'virConnect' object has no attribute 'baselineHypervisorCPU'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/details/details.py", line 1025, in hw_selected
    self.refresh_config_cpu()
  File "/usr/share/virt-manager/virtManager/details/details.py", line 2223, in refresh_config_cpu
    if not self._cpu_secure_is_available():
  File "/usr/share/virt-manager/virtManager/details/details.py", line 2167, in _cpu_secure_is_available
    features = domcaps.get_cpu_security_features()
  File "/usr/share/virt-manager/virtinst/domcapabilities.py", line 309, in get_cpu_security_features
    cpu = self._get_expanded_cpu(m)
  File "/usr/share/virt-manager/virtinst/domcapabilities.py", line 278, in _get_expanded_cpu
    expandedXML = self.conn.baselineHypervisorCPU(
  File "/usr/share/virt-manager/virtinst/connection.py", line 118, in __getattr__
    return getattr(libvirtconn, attr)
AttributeError: 'virConnect' object has no attribute 'baselineHypervisorCPU'

**Comment by Antique** [comment]
Hi, what is your OS and version of virt-manager and libvirt?

**Comment by bojansimicmb** [comment]
Hi, Ubuntu 18.04.3, virt-manager is 2.2.1 and libvirt 4.0.0

**Comment by Antique** [comment]
Thanks for the info, it confirms my suspicion. You have libvirt 4.0.0 and probably libvirt-python 4.0.0 where there is no `baselineHypervisorCPU` API.  I'll improve the code to properly handle this case and use older API if the new one is missing.  Thanks for the report.

**Comment by bojansimicmb** [comment]
Yes, python3-libvirt is 4.0.0. No problem.
