### ISSUE TITLE
Reboot required for Ubuntu, logout/login from the desktop environment is not enough

### ISSUE THREAD

**Issue by davidhedlund** [virt-manager/virt-manager#585]
# Issue
In Trisquel 11 (a distro based on Ubuntu 22.40) I only have to log out, and login in, to the desktop environment. But in Ubuntu (22.04, and 23.04), and Ubuntu MATE (22.04, and 23.04), I have to reboot.

* `$ sudo apt install virt-manager`
* Log out, and log in, from the desktop environment usually removes the below error (tested in Trisquel 11), but it did't work for Ubuntu MATE 23.04.

Open virt-manager:

![Screenshot_ubuntu-mate-23 04-desktop-amd64 iso_2023-09-23_19:38:13](https://github.com/virt-manager/virt-manager/assets/6416073/c997ac3d-fa66-42c2-8f2e-4ca36dd3d50e)
![Screenshot_ubuntu-mate-23 04-desktop-amd64 iso_2023-09-23_19:38:38](https://github.com/virt-manager/virt-manager/assets/6416073/cd1d7017-9951-450b-b894-06ce8f4517fa)

## Data
```
# The user is added to the libvirt group
$ groups x | grep libvirt
x : x adm cdrom sudo dip plugdev users lpadmin sambashare libvirt

$ systemctl status libvirtd.service
○ libvirtd.service - Virtualization daemon
     Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; preset: enabled)
     Active: inactive (dead) since Sat 2023-09-23 17:59:22 EDT; 13s ago
   Duration: 2min 33.820s
TriggeredBy: ● libvirtd-ro.socket
             ● libvirtd-admin.socket
             ● libvirtd.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
    Process: 4109 ExecStart=/usr/sbin/libvirtd $LIBVIRTD_ARGS (code=exited, status=0/SUCCESS)
   Main PID: 4109 (code=exited, status=0/SUCCESS)
      Tasks: 2 (limit: 32768)
     Memory: 4.3M
        CPU: 294ms
     CGroup: /system.slice/libvirtd.service
             ├─4221 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
             └─4222 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper

Sep 23 17:56:48 x-Standard-PC-Q35-ICH9-2009 dnsmasq-dhcp[4221]: DHCP, IP range 192.168.123.2 -- 192.168.123.254, lease time 1h
Sep 23 17:56:48 x-Standard-PC-Q35-ICH9-2009 dnsmasq-dhcp[4221]: DHCP, sockets bound exclusively to interface virbr0
Sep 23 17:56:48 x-Standard-PC-Q35-ICH9-2009 dnsmasq[4221]: reading /etc/resolv.conf
Sep 23 17:56:48 x-Standard-PC-Q35-ICH9-2009 dnsmasq[4221]: using nameserver 127.0.0.53#53
Sep 23 17:56:48 x-Standard-PC-Q35-ICH9-2009 dnsmasq[4221]: read /etc/hosts - 8 names
Sep 23 17:56:48 x-Standard-PC-Q35-ICH9-2009 dnsmasq[4221]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 names
Sep 23 17:56:48 x-Standard-PC-Q35-ICH9-2009 dnsmasq-dhcp[4221]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Sep 23 17:59:22 x-Standard-PC-Q35-ICH9-2009 systemd[1]: libvirtd.service: Deactivated successfully.
Sep 23 17:59:22 x-Standard-PC-Q35-ICH9-2009 systemd[1]: libvirtd.service: Unit process 4221 (dnsmasq) remains running after unit stopped.
Sep 23 17:59:22 x-Standard-PC-Q35-ICH9-2009 systemd[1]: libvirtd.service: Unit process 4222 (dnsmasq) remains running after unit stopped.
```

# User solution
* Reboot is required for all Ubuntu flavors and versions stated above. Screenshot from Ubuntu MATE 23.04

![Screenshot_ubuntu-mate-23 04-desktop-amd64 iso_2023-09-24_11:38:31](https://github.com/virt-manager/virt-manager/assets/6416073/aaf29e40-5d5e-4b2d-8c57-a98de8708990)

## Data

From Ubuntu 23.04, and Ubuntu MATE 23.04:
```
# Not added to more groups
$ groups x
x : x adm cdrom sudo dip plugdev users lpadmin sambashare libvirt

# The status is longer than earlier
$ systemctl status libvirtd.service
○ libvirtd.service - Virtualization daemon
     Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; preset: ena>
     Active: inactive (dead) since Sat 2023-09-23 18:06:01 EDT; 27s ago
   Duration: 2min 112ms
TriggeredBy: ● libvirtd.socket
             ● libvirtd-admin.socket
             ● libvirtd-ro.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
    Process: 746 ExecStart=/usr/sbin/libvirtd $LIBVIRTD_ARGS (code=exited, stat>
   Main PID: 746 (code=exited, status=0/SUCCESS)
      Tasks: 2 (limit: 32768)
     Memory: 18.4M
        CPU: 303ms
     CGroup: /system.slice/libvirtd.service
             ├─1061 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/defa>
             └─1063 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/defa>

Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq-dhcp[1061]: DHCP, IP range >
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq-dhcp[1061]: DHCP, sockets b>
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq[1061]: reading /etc/resolv.>
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq[1061]: using nameserver 127>
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq[1061]: read /etc/hosts - 8 >
lines 1-23...skipping...
○ libvirtd.service - Virtualization daemon
     Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; preset: enabled)
     Active: inactive (dead) since Sat 2023-09-23 18:06:01 EDT; 27s ago
   Duration: 2min 112ms
TriggeredBy: ● libvirtd.socket
             ● libvirtd-admin.socket
             ● libvirtd-ro.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
    Process: 746 ExecStart=/usr/sbin/libvirtd $LIBVIRTD_ARGS (code=exited, status=0/SUCCESS)
   Main PID: 746 (code=exited, status=0/SUCCESS)
      Tasks: 2 (limit: 32768)
     Memory: 18.4M
        CPU: 303ms
     CGroup: /system.slice/libvirtd.service
             ├─1061 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
             └─1063 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper

Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq-dhcp[1061]: DHCP, IP range 192.168.123.2 -- 192.168.123.254, lease time 1h
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq-dhcp[1061]: DHCP, sockets bound exclusively to interface virbr0
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq[1061]: reading /etc/resolv.conf
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq[1061]: using nameserver 127.0.0.53#53
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq[1061]: read /etc/hosts - 8 names
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq[1061]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 names
Sep 23 18:04:01 x-Standard-PC-Q35-ICH9-2009 dnsmasq-dhcp[1061]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Sep 23 18:06:01 x-Standard-PC-Q35-ICH9-2009 systemd[1]: libvirtd.service: Deactivated successfully.
Sep 23 18:06:01 x-Standard-PC-Q35-ICH9-2009 systemd[1]: libvirtd.service: Unit process 1061 (dnsmasq) remains running after unit stopped.
Sep 23 18:06:01 x-Standard-PC-Q35-ICH9-2009 systemd[1]: libvirtd.service: Unit process 1063 (dnsmasq) remains running after unit stopped.
```

# Question
* `sudo systemctl start libvirtd` didn't help. What is required?

# Development request
Make the libvirt/virt-manager post-install script start libvirtd, and add groups if needed.

# Distribution
Ubuntu MATE 23.04

```
$ apt show virt-manager
Package: virt-manager
Version: 1:4.1.0-2
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Libvirt Maintainers <pkg-libvirt-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2,351 kB
Depends: gir1.2-gtk-3.0 (>= 3.10), gir1.2-gtk-vnc-2.0, gir1.2-gtksource-4, gir1.2-libosinfo-1.0, gir1.2-libvirt-glib-1.0, gir1.2-vte-2.91, python3-gi (>= 3.31.3~), python3-gi-cairo, python3-libvirt (>= 0.7.1), virtinst (= 1:4.1.0-2), dconf-gsettings-backend | gsettings-backend, python3:any
Recommends: gir1.2-ayatanaappindicator3-0.1 | gir1.2-appindicator3-0.1, gir1.2-spiceclientglib-2.0, gir1.2-spiceclientgtk-3.0, libvirt-daemon-system (>= 1.2.7)
Suggests: gir1.2-secret-1, gnome-keyring, python3-guestfs, ssh-askpass, virt-viewer
Homepage: https://virt-manager.org/
Download-Size: 263 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu lunar/universe amd64 Packages
Description: desktop application for managing virtual machines
 The virt-manager application is a desktop user interface for managing virtual
 machines through libvirt. It primarily targets KVM VMs, but also manages Xen
 and LXC (Linux containers). It presents a summary view of running domains,
 their live performance & resource utilization statistics. Wizards enable the
 creation of new domains, and configuration & adjustment of a domain's resource
 allocation & virtual hardware. An embedded VNC and SPICE client viewer
 presents a full graphical console to the guest domain.
```

**Comment by ajgringo619** [comment]
Is your user a member of the `libvirt` group? May want to add it to the `libvirt-qemu` group as well.

What does `systemctl status libvirtd.service` return?

**Comment by davidhedlund** [comment]
> Is your user a member of the `libvirt` group? May want to add it to the `libvirt-qemu` group as well.
> 
> What does `systemctl status libvirtd.service` return?

I updated the top post. Thank you!

**Comment by davidhedlund** [comment]
> Is your user a member of the `libvirt` group? May want to add it to the `libvirt-qemu` group as well.

Yes, this affects Ubuntu 22.04, Ubuntu 23.04, Ubuntu MATE 22.04, and Ubuntu MATE 23.04.

> What does `systemctl status libvirtd.service` return?
I updated the top post with all details (2 hours work).

**Comment by ptoscano** [comment]
> > Is your user a member of the `libvirt` group? May want to add it to the `libvirt-qemu` group as well.
> 
> Yes, this affects Ubuntu 22.04, Ubuntu 23.04, Ubuntu MATE 22.04, and Ubuntu MATE 23.04.

Not sure how this answers the above question: the group needed in Ubuntu should be `libvirt-qemu`, _not_ `libvirt`.

You can verify that it works also using `virsh` (part of the `libvirt-clients` package):
```bash
$ virsh -c qemu:///system
```
if this works, then everything is fine.

In general, I see this more as Ubuntu question than a virt-manager one; because of that, I think this should be better asked in Ubuntu support channels, see https://ubuntu.com/community/support

Hence, closing. Thanks anyway for the report.

**Comment by davidhedlund** [comment]
> Not sure how this answers the above question: the group needed in Ubuntu should be `libvirt-qemu`, _not_ `libvirt`.

It's added to `libvirt` (see above screenshots. libvirt-qemu is not needed:

```
sudo usermod -a -G libvirt $(whoami)
newgrp libvirt

virsh -c qemu:///system
# Welcome to virsh, the virtualization interactive terminal.
# 
# Type:  'help' for help with commands
#        'quit' to quit
# 
# virsh # exit
```

However, when I open virt-manager, I get the error from the above screenshots.

**Comment by davidhedlund** [comment]
> > Not sure how this answers the above question: the group needed in Ubuntu should be `libvirt-qemu`, _not_ `libvirt`.
> 
> Users are added to the `libvirt` group (see above screenshots. libvirt-qemu is not needed:
> 
> ```
> sudo usermod -a -G libvirt $(whoami)
> newgrp libvirt
> 
> virsh -c qemu:///system
> # Welcome to virsh, the virtualization interactive terminal.
> # 
> # Type:  'help' for help with commands
> #        'quit' to quit
> # 
> # virsh # exit
> ```
> 
> However, when I open virt-manager, I get the error from the above screenshots:
> 
> ![image](https://user-images.githubusercontent.com/6416073/273369073-6be3ac96-9b44-4674-a695-766d90b6ee62.png)

When I click on "Details":
```
Unable to connect to libvirt qemu:///system.

Verify that the 'libvirtd' daemon is running.

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 923, in _do_open
    self._backend.open(cb, data)
  File "/usr/share/virt-manager/virtinst/connection.py", line 153, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/lib/python3/dist-packages/libvirt.py", line 148, in openAuth
    raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied
```
