### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by AliYar-Khan** [virt-manager/virt-manager#590]
**Distro**: 
While i run `python setup.py install` it gives me follow error : How can i solve this
```

running install
C:\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Using configured prefix=/usr instead of SYSPREFIX=C:\Python311
Traceback (most recent call last):
  File "C:\Users\acer\Downloads\Compressed\virt-manager-4.1.0.tar\virt-manager-4.1.0\setup.py", line 487, in <module>
    setuptools.setup(
  File "C:\Python311\Lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\Python311\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.ensure_finalized()
  File "C:\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "C:\Users\acer\Downloads\Compressed\virt-manager-4.1.0.tar\virt-manager-4.1.0\setup.py", line 264, in finalize_options
    setuptools.command.install.install.finalize_options(self)
  File "C:\Python311\Lib\site-packages\setuptools\command\install.py", line 45, in finalize_options
    orig.install.finalize_options(self)
  File "C:\Python311\Lib\site-packages\setuptools\_distutils\command\install.py", line 477, in finalize_options
    self.convert_paths(
  File "C:\Python311\Lib\site-packages\setuptools\_distutils\command\install.py", line 639, in convert_paths
    setattr(self, attr, convert_path(getattr(self, attr)))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
    raise ValueError("path '%s' cannot be absolute" % pathname)
ValueError: path '/usr/Lib/site-packages' cannot be absolute
```

**Comment by AliYar-Khan** [comment]
When i tried with --user flag like this `python setup.py install --user` 
the output is like this 
```
running install
C:\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Using configured prefix=/usr instead of SYSPREFIX=C:\Python311
error: can't combine user with prefix, exec_prefix/home, or install_(plat)base

```
there is some issue with prefix

**Comment by AliYar-Khan** [comment]
For the above error i go into virtinst directory and open the buildconfig.py file and change the 65 line number to below:

        `self._set_paths_by_prefix(_get_param("prefix", "c:\Python311"))`
    
    and then run this command 
        
`python setup.py install --prefix=c:\Python311` it gives me this error now

```
Generating C:\Users\acer\Downloads\Compressed\virt-manager-4.1.0.tar\virt-manager-4.1.0\build\virt-install
Generating C:\Users\acer\Downloads\Compressed\virt-manager-4.1.0.tar\virt-manager-4.1.0\build\virt-clone
Generating C:\Users\acer\Downloads\Compressed\virt-manager-4.1.0.tar\virt-manager-4.1.0\build\virt-xml
Generating C:\Users\acer\Downloads\Compressed\virt-manager-4.1.0.tar\virt-manager-4.1.0\build\virt-manager
Generating man\virt-clone.1
error: [WinError 193] %1 is not a valid Win32 application

```

How can i solve this ?

**Comment by crobinso** [comment]
Getting virt-manager to work on windows will take a lot of work. It depends on a lot of system libraries that aren't pure python. I know people have tried in the past to get things working but I don't know if anyone was ever successful.

**Comment by jcrben** [comment]
virt-manager can supposedly be installed via cygwin https://superuser.com/questions/1312058/use-virt-manager-on-windows-with-cygwin

I'm interested in getting it to work with the msys2 / mi ngw packages https://github.com/msys2/MINGW-packages

**Comment by AliYar-Khan** [comment]
@jcrben have your tried to actually do it? because I tried and I didn't succeeded!

**Comment by jcrben** [comment]
@AliYar-Khan I was able to install the virt-manager package on cygwin but it didn't work because the package is so ancient that it relies upon python2. Publishing an updated package may not be that difficult if you dig into it a bit.

* `scoop install msys2`
* `scoop install cygwin`
* `cygwin`
* `apt-cyg` - available but did not work so...
* `/cygdrive/c/Users/Ben/scoop/apps/cygwin/current/cygwin-setup`
  * select `virt-manager` from GUI
  * `virt-manager` - fails due to python2 issue

For updating, look at [Package: virt-manager](https://www.cygwin.com/packages/summary/virt-manager.html) and then consider this:
* has 1 small patch https://cygwin.com/cgit/cygwin-packages/virt-manager/tree/1.5.1-ayatana.patch
* [How to update a Cygwin package that has no maintainer?](https://stackoverflow.com/questions/71706931/how-to-update-a-cygwin-package-that-has-no-maintainer)

**Comment by jon-turney** [comment]
> I was able to install the virt-manager package on cygwin but it didn't work because the package is so ancient that it relies upon python2.

Since we occasionally get requests for it, I recently updated and rebuilt the virt-manager cygwin package for python3, and it seems to do something now. I wasn't able to do much testing, since it wants to connect to a qemu hypervisor I don't have...

Really virt-manager (and the libvirt stack) in cygwin needs a maintainer who actually uses it, or we should probably remove it to avoid giving people false hope that it works...

**Comment by AliYar-Khan** [comment]
We need an alternative for virt-manager on windows !!! I will research and starts if I get a lead

**Comment by jcrben** [comment]
@AliYar-Khan rather than trying to find an alternative, I would just focus on getting virt-manager working on Windows. once you get it working, more people may start using it who may be then motivated to lend more of a hand

**Comment by jon-turney** [comment]
> We need an alternative for virt-manager on windows !!! I will research and starts if I get a lead

I assume this means the updated cygwin package I made doesn't work, but without specifics nothing will change there...

**Comment by AliYar-Khan** [comment]
@jon-turney can you show how to install that ? I have seen [this](https://www.youtube.com/watch?v=gDEAu3oPcR0) video but it doesn't work

**Comment by Tarek-Hasan** [comment]
@jon-turney I saw that you updated cygwin vir-manager package for v2.2.1 from 2019. Why not version 4.x?

**Comment by jon-turney** [comment]
> Why not version 4.x?

If I recall correctly: that also required an update of libvirt and maybe other dependencies. That's not something I have the bandwith available to look into.

**Comment by Entropy512** [comment]
> Getting virt-manager to work on windows will take a lot of work. It depends on a lot of system libraries that aren't pure python. I know people have tried in the past to get things working but I don't know if anyone was ever successful.

Out of curiosity, how many of those dependencies would go away if virt-manager for Windows were set up to only support SSH connections to a remote libvirt instance?  I'm currently unfamiliar with libvirt's architecture regarding remote sessions, but a use case I have coming up is managing a remote Ubuntu Server VM host usng virt-manager since cockpit-machines is a little bit too feature-limited.  For the time being I'm working around this by running virt-manager from WSL2, but there are going to be some others in my organization who will likely not have WSL2 but will want to manage VMs on our host - although those VMs will probably already be configured so they can just use Cockpit...

**Comment by Tarek-Hasan** [comment]
@AliYar-Khan, just here to mention that, [QtEmu](https://gitlab.com/qtemu/gui) got revived. Version 3.0 beta released with Qt 6 and support for QEMU 9.x
