### ISSUE TITLE
tests are failing on python 3.12

### ISSUE THREAD

**Issue by Luciogi** [virt-manager/virt-manager#595]
**Distro**: void linux
logs 
```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.12.0, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/doggy/Git-repos/void-packages/masterdir/builddir/virt-manager-4.1.0
configfile: setup.cfg
testpaths: tests/
collected 543 items                                                                                                                                                                         

tests/test_capabilities.py .....                                                                                                                                                      [  0%]
tests/test_cloner.py ..                                                                                                                                                               [  1%]
tests/test_conn.py ...                                                                                                                                                                [  1%]
tests/test_disk.py ......                                                                                                                                                             [  2%]
tests/test_misc.py .......                                                                                                                                                            [  4%]
tests/test_nodedev.py ................                                                                                                                                                [  7%]
tests/test_osdict.py .......                                                                                                                                                          [  8%]
tests/test_storage.py ............                                                                                                                                                    [ 10%]
tests/test_uriparse.py ..                                                                                                                                                             [ 11%]
tests/test_urldetect.py .........                                                                                                                                                     [ 12%]
tests/test_xmlparse.py ..............................                                                                                                                                 [ 18%]
tests/test_cli.py .........................................................F.....................F..................................FF............................................... [ 48%]
..................................................................................................................................................................................... [ 81%]
..................................................................................................                                                                                    [ 99%]
tests/test_checkprops.py ss                                                                                                                                                           [100%]

========================================================================================= FAILURES ==========================================================================================
____________________________________________________________________________ testCLI0057virt_install_osinfo_url _____________________________________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 1645, in cmdtemplate
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 348, in run
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 345, in _run
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 292, in _check_compare_file
  File "/home/oggy/Git-repos/void-packages/masterdir/builddir/virt-manager-4.1.0/tests/utils.py", line 250, in diff_compare
    raise AssertionError("Conversion outputs did not match.\n%s" % diff)
AssertionError: Conversion outputs did not match.
--- tests/data/cli/compare/virt-install-osinfo-url.xml
+++ Generated output
@@ -13,7 +13,7 @@
     <type arch="x86_64" machine="q35">hvm</type>
     <kernel>/VIRTINST-TESTSUITE/vmlinuz</kernel>
     <initrd>/VIRTINST-TESTSUITE/initrd.img</initrd>
-    <cmdline>method=http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/26/Server/x86_64/os/</cmdline>
+    <cmdline>method=https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/26/Server/x86_64/os/</cmdline>
   </os>
   <features>
     <acpi/>

_______________________________________________________________________ testCLI0079virt_install_osinfo_url_with_disk ________________________________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 1645, in cmdtemplate
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 348, in run
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 345, in _run
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 292, in _check_compare_file
  File "/home/oggy/Git-repos/void-packages/masterdir/builddir/virt-manager-4.1.0/tests/utils.py", line 250, in diff_compare
    raise AssertionError("Conversion outputs did not match.\n%s" % diff)
AssertionError: Conversion outputs did not match.
--- tests/data/cli/compare/virt-install-osinfo-url-with-disk.xml
+++ Generated output
@@ -13,7 +13,7 @@
     <type arch="x86_64" machine="q35">hvm</type>
     <kernel>/VIRTINST-TESTSUITE/vmlinuz</kernel>
     <initrd>/VIRTINST-TESTSUITE/initrd.img</initrd>
-    <cmdline>method=http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/26/Server/x86_64/os/</cmdline>
+    <cmdline>method=https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/26/Server/x86_64/os/</cmdline>
   </os>
   <features>
     <acpi/>

_______________________________________________________________________ testCLI0114virt_install_osinfo_url_unattended _______________________________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 1645, in cmdtemplate
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 348, in run
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 345, in _run
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 292, in _check_compare_file
  File "/home/oggy/Git-repos/void-packages/masterdir/builddir/virt-manager-4.1.0/tests/utils.py", line 250, in diff_compare
    raise AssertionError("Conversion outputs did not match.\n%s" % diff)
AssertionError: Conversion outputs did not match.
--- tests/data/cli/compare/virt-install-osinfo-url-unattended.xml
+++ Generated output
@@ -13,7 +13,7 @@
     <type arch="x86_64" machine="q35">hvm</type>
     <kernel>/VIRTINST-TESTSUITE/vmlinuz</kernel>
     <initrd>/VIRTINST-TESTSUITE/initrd.img</initrd>
-    <cmdline>ks=file:/fedora.ks inst.repo=http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/26/Server/x86_64/os/</cmdline>
+    <cmdline>ks=file:/fedora.ks inst.repo=https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/26/Server/x86_64/os/</cmdline>
   </os>
   <features>
     <acpi/>

____________________________________________________________________ testCLI0115virt_install_osinfo_unattended_treeapis _____________________________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 1645, in cmdtemplate
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 348, in run
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 345, in _run
  File "/builddir/virt-manager-4.1.0/tests/test_cli.py", line 292, in _check_compare_file
  File "/home/oggy/Git-repos/void-packages/masterdir/builddir/virt-manager-4.1.0/tests/utils.py", line 250, in diff_compare
    raise AssertionError("Conversion outputs did not match.\n%s" % diff)
AssertionError: Conversion outputs did not match.
--- tests/data/cli/compare/virt-install-osinfo-unattended-treeapis.xml
+++ Generated output
@@ -13,7 +13,7 @@
     <type arch="x86_64" machine="pc-i440fx-6.1">hvm</type>
     <kernel>/VIRTINST-TESTSUITE/vmlinuz</kernel>
     <initrd>/VIRTINST-TESTSUITE/initrd.img</initrd>
-    <cmdline>ks=file:/fedora.ks method=http://archive.fedoraproject.org/pub/archive/fedora/linux/releases/17/Fedora/x86_64/os/</cmdline>
+    <cmdline>ks=file:/fedora.ks method=https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/17/Fedora/x86_64/os/</cmdline>
   </os>
   <features>
     <acpi/>

================================================================================== short test summary info ==================================================================================
FAILED tests/test_cli.py::testCLI0057virt_install_osinfo_url - AssertionError: Conversion outputs did not match.
FAILED tests/test_cli.py::testCLI0079virt_install_osinfo_url_with_disk - AssertionError: Conversion outputs did not match.
FAILED tests/test_cli.py::testCLI0114virt_install_osinfo_url_unattended - AssertionError: Conversion outputs did not match.
FAILED tests/test_cli.py::testCLI0115virt_install_osinfo_unattended_treeapis - AssertionError: Conversion outputs did not match.
========================================================================= 4 failed, 537 passed, 2 skipped in 19.99s =========================================================================


```

**Comment by ptoscano** [comment]
The test failures are not related to Python, rather to newer versions of osinfo-db that change some http URLs to https; this was fixed with commit 6e5c1db6b4a0af96afeb09a09fb2fc2b73308f01, so try to cherry-pick that to see whether it fixes the unit tests.
