### ISSUE TITLE
Not working after Ubuntu update 

### ISSUE THREAD

**Issue by mayday77** [virt-manager/virt-manager#602]
There is an error

virt-manager
Traceback (most recent call last):
  File "/usr/bin/virt-manager", line 6, in <module>
    from virtManager import virtmanager
  File "/usr/share/virt-manager/virtManager/virtmanager.py", line 19, in <module>
    from virtinst import BuildConfig
  File "/usr/share/virt-manager/virtinst/__init__.py", line 60, in <module>
    from virtinst.install.installer import Installer
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 12, in <module>
    from . import unattended
  File "/usr/share/virt-manager/virtinst/install/unattended.py", line 18, in <module>
    from . import urlfetcher
  File "/usr/share/virt-manager/virtinst/install/urlfetcher.py", line 16, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 144, in <module>
    from . import packages, utils
  File "/usr/lib/python3/dist-packages/requests/packages.py", line 8, in <module>
    locals()[package] = __import__(package)
                        ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'idna'

Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar

**Distro**: Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar

**Comment by mayday77** [comment]
sorry , was fixed by 
 **pip install idna --break-system-packages**

**Comment by ptoscano** [comment]
Hi @mayday77,

what you report seems like an issue in Ubuntu, so please report it to Ubuntu directly.

Thanks anyway for your report.
