### ISSUE TITLE
Entering the startup virtual machine prompts libsoup error

### ISSUE THREAD

**Issue by chenchongbiao** [virt-manager/virt-manager#608]
Hi,

I am using Virtual Manager 4.1.0 on an deepin Linux PC.

It is possible to start the virtual machine, but when double clicking to enter the interface, an error message 'libsoup Error * *: 15:52:41.851: libsoup2 symbols detected' will appear Using libsoup2 and libsoup3 in the same process is not supported

virt-viewer can be used normally

**Distro**:  deepin beige
**Package**: 
> python3-gi=3.46.0-1
> qemu-system=1:8.1.2+ds
> libsoup2.4-1=2.74.2-3
> libsoup-3.0-0=3.4.3-1
> libglib2.0-0=2.78.0-2
> libvirt-daemon-system=9.8.0-1
> gobject-introspection=1.78.1-1
> gir1.2-spiceclientgtk-3.0=0.42-2
> python3-libvirt=9.0.0-1

```bash
# Log

[五, 08 12月 2023 15:51:00 virt-manager 252209] DEBUG (vmwindow:185) Showing VM details: <vmmDomain name=deepin id=0x7f0b782a34c0>
[五, 08 12月 2023 15:51:00 virt-manager 252209] DEBUG (engine:316) window counter incremented to 2
[五, 08 12月 2023 15:51:00 virt-manager 252209] DEBUG (console:721) Starting connect process for proto=spice trans= connhost=127.0.0.1 connuser= connport= gaddr=0.0.0.0 gport=5900 gtlsport=None gsocket=None

(virt-manager:252209): libsoup-ERROR **: 15:51:00.442: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
[1]    252209 trace trap (core dumped)  virt-manager --debug
```

```bash
# coredeump 

(gdb) bt
#0  0x00007fe856bbf787 in g_log_structured_array () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fe856bbfbde in g_log_default_handler () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fe856bbfe50 in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fe856bc00ff in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fe84c081c2c in soup_init () at ../libsoup/soup-init.c:55
#5  soup_init_ctor () at ../libsoup/soup-init.c:96
#6  0x00007fe857566cfe in  () at /lib64/ld-linux-x86-64.so.2
#7  0x00007fe857566de4 in  () at /lib64/ld-linux-x86-64.so.2
#8  0x00007fe857563516 in _dl_catch_exception () at /lib64/ld-linux-x86-64.so.2
#9  0x00007fe85756d47e in  () at /lib64/ld-linux-x86-64.so.2
#10 0x00007fe857563489 in _dl_catch_exception () at /lib64/ld-linux-x86-64.so.2
#11 0x00007fe85756d7f8 in  () at /lib64/ld-linux-x86-64.so.2
#12 0x00007fe8572b1ef8 in  () at /lib/x86_64-linux-gnu/libc.so.6
#13 0x00007fe857563489 in _dl_catch_exception () at /lib64/ld-linux-x86-64.so.2
#14 0x00007fe8575635af in  () at /lib64/ld-linux-x86-64.so.2
#15 0x00007fe8572b1a07 in  () at /lib/x86_64-linux-gnu/libc.so.6
#16 0x00007fe8572b1fa9 in dlopen () at /lib/x86_64-linux-gnu/libc.so.6
#17 0x00007fe85753f91b in g_module_open_full () at /lib/x86_64-linux-gnu/libgmodule-2.0.so.0
#18 0x00007fe856adcf55 in load_one_shared_library (shlib=0x5a54820 "libspice-client-glib-2.0.so.8")
    at ../girepository/gitypelib.c:2294
#19 _g_typelib_do_dlopen (typelib=0x2935770) at ../girepository/gitypelib.c:2326
#20 _g_typelib_ensure_open (typelib=0x2935770) at ../girepository/gitypelib.c:2362
#21 g_typelib_symbol
    (typelib=0x2935770, symbol_name=symbol_name@entry=0x7fe84d718a34 "spice_session_get_type", symbol=symbol@entry=0x7ffe1fe68010) at ../girepository/gitypelib.c:2505
#22 0x00007fe856ad5d1b in g_registered_type_info_get_g_type (info=0x5af6af0)
    at ../girepository/giregisteredtypeinfo.c:136
#23 0x00007fe856cc41fd in  () at /usr/lib/python3/dist-packages/gi/_gi.cpython-311-x86_64-linux-gnu.so
#24 0x000000000051973c in  ()
#25 0x000000000053343c in PyObject_Vectorcall ()
#26 0x000000000052549a in _PyEval_EvalFrameDefault ()
#27 0x0000000000577fca in  ()
#28 0x0000000000577744 in  ()
#29 0x00000000005bf9b3 in  ()
#30 0x00000000005bf3b2 in  ()
#31 0x00000000005183fa in PyObject_GetAttr ()
#32 0x0000000000525b7c in _PyEval_EvalFrameDefault ()
#33 0x0000000000577fca in  ()
--Type <RET> for more, q to quit, c to continue without paging--c
#34 0x0000000000577718 in  ()
#35 0x000000000052922f in _PyEval_EvalFrameDefault ()
#36 0x0000000000551c9d in _PyFunction_Vectorcall ()
#37 0x00007fe856cc145b in  ()
    at /usr/lib/python3/dist-packages/gi/_gi.cpython-311-x86_64-linux-gnu.so
#38 0x00007fe85754ae35 in  () at /lib/x86_64-linux-gnu/libffi.so.8
#39 0x00007fe85754b1b0 in  () at /lib/x86_64-linux-gnu/libffi.so.8
#40 0x00007fe856bb45e9 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007fe856bb7757 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007fe856bb7d4c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007fe85692ba1d in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#44 0x00007fe85754b01a in  () at /lib/x86_64-linux-gnu/libffi.so.8
#45 0x00007fe85754a4be in  () at /lib/x86_64-linux-gnu/libffi.so.8
#46 0x00007fe85754abad in ffi_call () at /lib/x86_64-linux-gnu/libffi.so.8
#47 0x00007fe856cca119 in  ()
    at /usr/lib/python3/dist-packages/gi/_gi.cpython-311-x86_64-linux-gnu.so
#48 0x00007fe856cc07f8 in  ()
    at /usr/lib/python3/dist-packages/gi/_gi.cpython-311-x86_64-linux-gnu.so
#49 0x000000000055ecd6 in PyObject_Call ()
#50 0x000000000052922f in _PyEval_EvalFrameDefault ()
#51 0x00000000005f9bbb in PyEval_EvalCode ()
#52 0x00000000006140e7 in  ()
#53 0x0000000000610fdf in  ()
#54 0x00000000006225d2 in  ()
#55 0x000000000062234d in _PyRun_SimpleFileObject ()
#56 0x0000000000622164 in _PyRun_AnyFileObject ()
#57 0x0000000000620af7 in Py_RunMain ()
#58 0x00000000005ed297 in Py_BytesMain ()
#59 0x00007fe85725578a in  () at /lib/x86_64-linux-gnu/libc.so.6
#60 0x00007fe857255845 in __libc_start_main () at /lib/x86_64-linux-gnu/libc.so.6
#61 0x00000000005ed131 in _start ()
```

Regards

**Comment by ptoscano** [comment]
Hi @chenchongbiao,

> It is possible to start the virtual machine, but when double clicking to enter the interface, an error message 'libsoup Error * *: 15:52:41.851: libsoup2 symbols detected' will appear Using libsoup2 and libsoup3 in the same process is not supported

This means that some packages in the stack of the virtualization packages (e.g. libosinfo, SPICE, librest) were built with soup v2, and others with soup v3. This combination is not supported, and it leads to symbols conflicts.

Please report this problem to your distribution, so they can properly build everything using only one version of soup.
