### ISSUE TITLE
can't clone VMs if a cursor theme was not found

### ISSUE THREAD

**Issue by IbrahimOuhamou** [virt-manager/virt-manager#638]
the pop-up window for cloning closes after opening, running $`virt-manager --no-fork` it shows that it is because the theme was not found **can't it suppress the error instead of crashing the pop-up?**

here is the output:

```
Gdk-Message: 17:39:44.223: Unable to load col-resize from the cursor theme
Gdk-Message: 17:39:44.223: Unable to load col-resize from the cursor theme
Gdk-Message: 17:39:44.223: Unable to load col-resize from the cursor theme
Gdk-Message: 17:39:44.223: Unable to load col-resize from the cursor theme
Gdk-Message: 17:39:44.223: Unable to load col-resize from the cursor theme
Gdk-Message: 17:39:44.223: Unable to load col-resize from the cursor theme
Gdk-Message: 17:40:01.308: Unable to load col-resize from the cursor theme
Gdk-Message: 17:40:01.308: Unable to load col-resize from the cursor theme
Gdk-Message: 17:40:02.623: Unable to load progress from the cursor theme
Gdk-Message: 17:40:02.630: Unable to load progress from the cursor theme
Traceback (most recent call last):
  File "/nix/store/7j8ydnlcg4fmmshsgqqi0sqlpwawpnbn-virt-manager-4.1.0/share/virt-manager/virtManager/clone.py", line 588, in _finish_clicked_cb
    return self._finish()
           ^^^^^^^^^^^^^^
  File "/nix/store/7j8ydnlcg4fmmshsgqqi0sqlpwawpnbn-virt-manager-4.1.0/share/virt-manager/virtManager/clone.py", line 578, in _finish
    progWin.run()
  File "/nix/store/7j8ydnlcg4fmmshsgqqi0sqlpwawpnbn-virt-manager-4.1.0/share/virt-manager/virtManager/asyncjob.py", line 270, in run
    Gdk.Cursor.new_from_name(gdk_window.get_display(), "progress"))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: constructor returned NULL
```

**DISTRO NIXOS**

**Comment by phrdina** [comment]
/duplicate https://github.com/virt-manager/virt-manager/issues/479

**Comment by phrdina** [comment]
Duplicate of 479
