### ISSUE TITLE
macOS: gi.RepisotiryError: Typelib file for namespace 'GLib', version '2.0' not found

### ISSUE THREAD

**Issue by BBaoVanC** [virt-manager/virt-manager#649]
**Distro**: macOS Sonoma 14.4.1
**Architecture**: Intel x86_64

I just updated my system with Homebrew and now virt-manager does not start. Unsure if this is related to #620. I also don't know what dependency I updated to break virt-manager because Homebrew does not seem to have any logs and there were about 100 packages updated. Also tried on latest git (4ffbc0d904439aa5d5f818a2ece23bf95969ae98) and I get the same error.

```console
$ ./virt-manager --debug
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gi/importer.py", line 139, in create_module
    introspection_module = get_introspection_module(namespace)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gi/module.py", line 263, in get_introspection_module
    module = IntrospectionModule(namespace, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gi/module.py", line 110, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'GLib', version '2.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/virt-manager", line 6, in <module>
    from virtManager import virtmanager
  File "/usr/local/Cellar/virt-manager/4.1.0_4/share/virt-manager/virtManager/virtmanager.py", line 17, in <module>
    from gi.repository import LibvirtGLib
  File "/usr/local/lib/python3.11/site-packages/gi/importer.py", line 141, in create_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'GLib', version '2.0' not found
```

**Comment by cetzold** [comment]
For me
`brew link glib`
did the trick.

```
brew doctor
...
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  glib
...
```

**Comment by BBaoVanC** [comment]
> For me
> `brew link glib`
> did the trick.

Interesting, I must've missed it in the mass of messages it tells you when brew finishes. Not a virt-manager issue then I guess.
