### ISSUE TITLE
libxml2 specific version not found

### ISSUE THREAD

**Issue by Sarcasthik** [virt-manager/virt-manager#696]
**Distro**: ubuntu 22.04. LTS

Hello,
I'm having an issue with simply starting virt-manager. Today I am getting this error even when running from cloned repo : 

```
user@homeserver:~/virt-manager$ ./virt-manager --debug
Traceback (most recent call last):
  File "/home/user/virt-manager/./virt-manager", line 8, in <module>
    from virtManager import virtmanager
  File "/home/user/virt-manager/./virtManager/virtmanager.py", line 19, in <module>
    from virtinst import BuildConfig
  File "/home/user/virt-manager/./virtinst/__init__.py", line 50, in <module>
    from virtinst.domain import *  # pylint: disable=wildcard-import
  File "/home/user/virt-manager/./virtinst/domain/__init__.py", line 5, in <module>
    from .blkiotune import DomainBlkiotune
  File "/home/user/virt-manager/./virtinst/domain/blkiotune.py", line 8, in <module>
    from ..xmlbuilder import XMLBuilder, XMLChildProperty, XMLProperty
  File "/home/user/virt-manager/./virtinst/xmlbuilder.py", line 16, in <module>
    from .xmlapi import XMLAPI
  File "/home/user/virt-manager/./virtinst/xmlapi.py", line 7, in <module>
    import libxml2
  File "/usr/lib/python3/dist-packages/libxml2.py", line 1, in <module>
    import libxml2mod
ImportError: /usr/lib/vmware/libxml2.so.2: version `LIBXML2_2.9.11' not found (required by /usr/lib/python3/dist-packages/libxml2mod.cpython-310-x86_64-linux-gnu.so)
```
I've tried uninstalling/purging reinstalling the below packages but nothing will do. Here are the packages versions : 

`ii  virt-manager   1:4.0.0-1    all          desktop application for managing virtual machines`
`ii  libxml2:amd64  2.9.13+dfsg-1ubuntu0.4 amd64        GNOME XML library`

Any ideas ? Thanks !

**Comment by Sarcasthik** [comment]
I hate when I find the solution right after posting, so for anyone having the same issue, add the line below at the end of your ~/.bashrc or ~/.profile file and reload :

`export LD_LIBRARY_PATH=/usr/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH`
`source ~/.bashrc` or `source ~/.profile`

cheers
