### ISSUE TITLE
cannot run with qemu v9.1.2 due to error "qemu-system-x86_64: -no-hpet: invalid option"

### ISSUE THREAD

**Issue by weiklr** [virt-manager/virt-manager#772]
**Distro**: 
Pop OS 22.04

I'm running qemu v 9.1.2, virt-manager 4.0.0

Wnen I try to create a VM. It failed with the error: "qemu-system-x86_64: -no-hpet: invalid option"

Here's the logs:

Unable to complete install: 'internal error: qemu unexpectedly closed the monitor: qemu-system-x86_64: -no-hpet: invalid option'

```
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4400, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: qemu-system-x86_64: -no-hpet: invalid option
```

Should i use virt-manager 4.1.0 instead?

**Comment by phrdina** [comment]
That will not help. This error message comes from libvirt. Pop OS is based on Ubuntu and Ubuntu 22.04 has old libvirt. You will need to update libvirt. The `-no-hpet` option was removed in QEMU 9.0.0 and it was fixed in libvirt 9.0.0.
