### ISSUE TITLE
xen virt-manager create virt-machine failed with an unknown error?

### ISSUE THREAD

**Issue by Yurii-huang** [virt-manager/virt-manager#774]
```bash
[Mon, 25 Nov 2024 14:25:31 virt-manager 3852] DEBUG (installer:314) Generated boot XML: 
<domain type="xen">
  <name>testopeneuler</name>
  <uuid>4ccd4a65-6f01-4986-afae-8d0249796eb4</uuid>
  <memory>4194304</memory>
  <currentMemory>4194304</currentMemory>
  <vcpu>4</vcpu>
  <os>
    <type arch="x86_64" machine="xenfv">hvm</type>
    <loader>/usr/lib/xen-4.11/boot/hvmloader</loader>
    <boot dev="cdrom"/>
    <boot dev="hd"/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <clock offset="utc"/>
  <devices>
    <emulator>/usr/lib/xen-4.11/bin/qemu-system-i386</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="/var/lib/libvirt/images/testxen.qcow2"/>
      <target dev="hda" bus="ide"/>
    </disk>
    <disk type="file" device="cdrom">
      <target dev="hdb" bus="ide"/>
      <readonly/>
    </disk>
    <interface type="network">
      <source network="default"/>
      <mac address="00:16:3e:82:fb:c1"/>
    </interface>
    <console type="pty"/>
    <input type="keyboard" bus="usb"/>
    <input type="mouse" bus="usb"/>
    <graphics type="vnc" port="-1"/>
    <video>
      <model type="vga"/>
    </video>
  </devices>
</domain>

[Mon, 25 Nov 2024 14:25:31 virt-manager 3852] DEBUG (error:83) error dialog message:
summary=Unable to complete install: 'An error occurred, but the cause is unknown'
details=Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/create.py", line 2121, in _do_async_install
    guest.installer_instance.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/installer.py", line 419, in start_install
    doboot, transient)
  File "/usr/share/virt-manager/virtinst/installer.py", line 362, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 3732, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: An error occurred, but the cause is unknown
```
How?

**Comment by phrdina** [comment]
Hi, thanks for the report but this is most likely not virt-manager issue. That error comes from libvirt, please report the issue here https://gitlab.com/libvirt/libvirt/-/issues. When you report an issue it is important to provide version of affected projects and ideally your OS and its version as well.
