### ISSUE TITLE
testCLI0006virt_install_memory_hotplug fails on loongaarch64 

### ISSUE THREAD

**Issue by chereskata** [virt-manager/virt-manager#781]
Hi,

after trying to package the latest `virt-manager` for Alpine Linux ([MR](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/76357)), i encountered an issue with the `testCLI0006virt_install_memory_hotplug` Test.

It shows following error output:

<details><summary> Shortlog </summary>

```
=================================== FAILURES ===================================
____________________ testCLI0006virt_install_memory_hotplug ____________________
Traceback (most recent call last):
  File "/builds/chereskata/aports/community/virt-manager/src/virt-manager-5.0.0/tests/test_cli.py", line 320, in _check_compare_file
    dom = conn.defineXML(domxml)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/chereskata/aports/community/virt-manager/src/virt-manager-5.0.0/virtinst/uri.py", line 218, in newdefine
    return origdefine(xml)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libvirt.py", line 4559, in defineXML
    raise libvirtError('virDomainDefineXML() failed')
libvirt.libvirtError: block size too small, must be at least 32768KiB
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
                             ^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/threadexception.py", line 92, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/usr/lib/python3.12/site-packages/_pytest/threadexception.py", line 68, in thread_exception_runtest_hook
    yield
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 95, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/usr/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 70, in unraisable_exception_runtest_hook
    yield
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/logging.py", line 846, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/usr/lib/python3.12/site-packages/_pytest/logging.py", line 829, in _runtest_for
    yield
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/capture.py", line 880, in pytest_runtest_call
    return (yield)
            ^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/skipping.py", line 257, in pytest_runtest_call
    return (yield)
            ^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/chereskata/aports/community/virt-manager/src/virt-manager-5.0.0/tests/test_cli.py", line 1777, in cmdtemplate
    cmd.run()
  File "/builds/chereskata/aports/community/virt-manager/src/virt-manager-5.0.0/tests/test_cli.py", line 363, in run
    self._run()
  File "/builds/chereskata/aports/community/virt-manager/src/virt-manager-5.0.0/tests/test_cli.py", line 360, in _run
    self._check_compare_file(conn, output)
  File "/builds/chereskata/aports/community/virt-manager/src/virt-manager-5.0.0/tests/test_cli.py", line 324, in _check_compare_file
    raise AssertionError("Bad XML:\n%s\n\nError was: %s: %s" %
AssertionError: Bad XML:
<domain type="kvm">
  <name>fedora</name>
  <uuid>00000000-1111-2222-3333-444444444444</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://fedoraproject.org/fedora/unknown"/>
    </libosinfo:libosinfo>
  </metadata>
  <maxMemory slots="3">4194304</maxMemory>
  <vcpu>2</vcpu>
  <os>
    <type arch="x86_64" machine="q35">hvm</type>
    <boot dev="network"/>
    <boot dev="hd"/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state="off"/>
  </features>
  <cpu mode="host-passthrough">
    <numa>
      <cell cpus="0" memory="1048576"/>
    </numa>
  </cpu>
  <clock offset="utc">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
  </clock>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2" discard="unmap"/>
      <source file="/var/lib/libvirt/images/fedora.qcow2"/>
      <target dev="vda" bus="virtio"/>
    </disk>
    <controller type="usb" model="qemu-xhci" ports="15"/>
    <controller type="pci" model="pcie-root"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <interface type="bridge">
      <source bridge="testsuitebr0"/>
      <mac address="00:11:22:33:44:55"/>
      <model type="virtio"/>
    </interface>
    <console type="pty"/>
    <channel type="unix">
      <source mode="bind"/>
      <target type="virtio" name="org.qemu.guest_agent.0"/>
    </channel>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
    </channel>
    <input type="tablet" bus="usb"/>
    <graphics type="spice" port="-1" tlsPort="-1" autoport="yes">
      <image compression="off"/>
    </graphics>
    <sound model="ich9"/>
    <video>
      <model type="virtio"/>
    </video>
    <redirdev bus="usb" type="spicevmc"/>
    <redirdev bus="usb" type="spicevmc"/>
    <memballoon model="virtio"/>
    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
    </rng>
    <memory model="dimm" access="private" discard="yes">
      <source>
        <pagesize>4</pagesize>
        <nodemask>1-2</nodemask>
      </source>
      <target>
        <size>262144</size>
        <node>0</node>
      </target>
    </memory>
    <memory model="dimm" access="private" discard="yes">
      <source>
        <pagesize>4</pagesize>
        <nodemask>1-2</nodemask>
      </source>
      <target>
        <size>262144</size>
        <node>0</node>
      </target>
    </memory>
    <memory model="nvdimm">
      <alias name="mymemdev3"/>
      <address type="dimm" slot="1" base="0x100000000"/>
      <source>
        <path>/path/to/nvdimm</path>
        <pmem/>
        <alignsize>2097152</alignsize>
      </source>
      <target>
        <size>524288</size>
        <node>0</node>
        <label>
          <size>131072</size>
        </label>
        <block>2048</block>
        <current>524288</current>
        <requested>1048576</requested>
        <readonly/>
      </target>
    </memory>
    <memory model="virtio-mem">
      <target>
        <size>524288</size>
        <node>0</node>
        <block>2048</block>
        <requested>524288</requested>
        <address base="0x180000000"/>
      </target>
    </memory>
    <memory model="virtio-pmem">
      <source>
        <path>/tmp/virtio_pmem</path>
      </source>
      <target>
        <size>524288</size>
        <address base="0x1a0000000"/>
      </target>
    </memory>
  </devices>
  <on_reboot>destroy</on_reboot>
</domain>
Error was: libvirtError: block size too small, must be at least 32768KiB
=========================== short test summary info ============================
FAILED tests/test_cli.py::testCLI0006virt_install_memory_hotplug - AssertionError: Bad XML:
<domain type="kvm">
  <name>fedora</name>
  <uuid>00000000-1111-2222-3333-444444444444</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://fedoraproject.org/fedora/unknown"/>
    </libosinfo:libosinfo>
  </metadata>
  <maxMemory slots="3">4194304</maxMemory>
  <vcpu>2</vcpu>
  <os>
    <type arch="x86_64" machine="q35">hvm</type>
    <boot dev="network"/>
    <boot dev="hd"/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state="off"/>
  </features>
  <cpu mode="host-passthrough">
    <numa>
      <cell cpus="0" memory="1048576"/>
    </numa>
  </cpu>
  <clock offset="utc">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
  </clock>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2" discard="unmap"/>
      <source file="/var/lib/libvirt/images/fedora.qcow2"/>
      <target dev="vda" bus="virtio"/>
    </disk>
    <controller type="usb" model="qemu-xhci" ports="15"/>
    <controller type="pci" model="pcie-root"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <interface type="bridge">
      <source bridge="testsuitebr0"/>
      <mac address="00:11:22:33:44:55"/>
      <model type="virtio"/>
    </interface>
    <console type="pty"/>
    <channel type="unix">
      <source mode="bind"/>
      <target type="virtio" name="org.qemu.guest_agent.0"/>
    </channel>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
    </channel>
    <input type="tablet" bus="usb"/>
    <graphics type="spice" port="-1" tlsPort="-1" autoport="yes">
      <image compression="off"/>
    </graphics>
    <sound model="ich9"/>
    <video>
      <model type="virtio"/>
    </video>
    <redirdev bus="usb" type="spicevmc"/>
    <redirdev bus="usb" type="spicevmc"/>
    <memballoon model="virtio"/>
    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
    </rng>
    <memory model="dimm" access="private" discard="yes">
      <source>
        <pagesize>4</pagesize>
        <nodemask>1-2</nodemask>
      </source>
      <target>
        <size>262144</size>
        <node>0</node>
      </target>
    </memory>
    <memory model="dimm" access="private" discard="yes">
      <source>
        <pagesize>4</pagesize>
        <nodemask>1-2</nodemask>
      </source>
      <target>
        <size>262144</size>
        <node>0</node>
      </target>
    </memory>
    <memory model="nvdimm">
      <alias name="mymemdev3"/>
      <address type="dimm" slot="1" base="0x100000000"/>
      <source>
        <path>/path/to/nvdimm</path>
        <pmem/>
        <alignsize>2097152</alignsize>
      </source>
      <target>
        <size>524288</size>
        <node>0</node>
        <label>
          <size>131072</size>
        </label>
        <block>2048</block>
        <current>524288</current>
        <requested>1048576</requested>
        <readonly/>
      </target>
    </memory>
    <memory model="virtio-mem">
      <target>
        <size>524288</size>
        <node>0</node>
        <block>2048</block>
        <requested>524288</requested>
        <address base="0x180000000"/>
      </target>
    </memory>
    <memory model="virtio-pmem">
      <source>
        <path>/tmp/virtio_pmem</path>
      </source>
      <target>
        <size>524288</size>
        <address base="0x1a0000000"/>
      </target>
    </memory>
  </devices>
  <on_reboot>destroy</on_reboot>
</domain>
Error was: libvirtError: block size too small, must be at least 32768KiB
====== 1 failed, 577 passed, 17 skipped, 2 deselected in 72.89s (0:01:12) ======
```

</details>

Whole pipeline [here](https://gitlab.alpinelinux.org/chereskata/aports/-/jobs/1632086/raw)

Thanks :)

**Comment by phrdina** [comment]
Hi, thanks for the report. So the issue here is that on loongarch64 the value that libvirt gets from `/sys/kernel/mm/transparent_hugepage/hpage_pmd_size` is `32768KiB`. Libvirt doesn't report this value anywhere so we have no way how to figure out that value.

We could change the tests to use this new value but same issue can happen in future.

Because you already skip that test case when building package for Alpine linux I'm not sure if it's worth fixing.
