### ISSUE TITLE
Unable to create virtual machine

### ISSUE THREAD

**Issue by skjsbsnq** [virt-manager/virt-manager#782]
无法完成安装：'读取数据时进入文件终点: 输入/输出错误'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libvirt.py", line 4545, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: 读取数据时进入文件终点: 输入/输出错误

**Comment by skjsbsnq** [comment]
I will provide more information if needed

**Comment by phrdina** [comment]
Hi, thanks for the report. After translating the error message it looks like this is issue in libvirt. Please report it here https://gitlab.com/libvirt/libvirt/-/issues and always provide details about your OS, project version and steps to reproduce the issue.
