### ISSUE TITLE
Unable to Automatically Create Windows 11 Virtual Machines on Alpine Linux

### ISSUE THREAD

**Issue by NN708** [virt-manager/virt-manager#793]
**Distro**: Alpine Linux 3.21

I am experiencing an issue when attempting to automatically create Windows 11 virtual machines using virt-manager version 5.0.0 installed via Flatpak, which is connected to an x86_64 Alpine Linux 3.21 host.

Error log:
```
Unable to complete install: 'Failed to open file '/usr/share/qemu/edk2-i386-vars.fd': No such file or directory'

Traceback (most recent call last):
  File "/app/share/virt-manager/virtManager/asyncjob.py", line 71, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/app/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/app/share/virt-manager/virtinst/install/installer.py", line 726, in start_install
    domain = self._create_guest(
             ^^^^^^^^^^^^^^^^^^^
  File "/app/share/virt-manager/virtinst/install/installer.py", line 667, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/libvirt.py", line 4545, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: Failed to open file '/usr/share/qemu/edk2-i386-vars.fd': No such file or directory
```

Files on the host:
```console
$ ls -l /usr/share/qemu
total 15220
-rw-r--r--    1 root     root           850 Nov 29 23:13 QEMU,cgthree.bin
-rw-r--r--    1 root     root          1402 Nov 29 23:13 QEMU,tcx.bin
-rw-r--r--    1 root     root          3211 Nov 29 23:13 bamboo.dtb
-rw-r--r--    1 root     root        262144 Nov 29 23:13 bios-256k.bin
-rw-r--r--    1 root     root        131072 Nov 29 23:13 bios-microvm.bin
-rw-r--r--    1 root     root        131072 Nov 29 23:13 bios.bin
-rw-r--r--    1 root     root          9779 Nov 29 23:13 canyonlands.dtb
-rw-r--r--    1 root     root         42903 Nov 29 23:13 edk2-licenses.txt
-rw-r--r--    1 root     root       3653632 Nov 29 23:13 edk2-x86_64-code.fd
-rw-r--r--    1 root     root       3653632 Nov 29 23:13 edk2-x86_64-secure-code.fd
-rw-r--r--    1 root     root        159232 Nov 29 23:13 efi-e1000.rom
-rw-r--r--    1 root     root        159232 Nov 29 23:13 efi-e1000e.rom
-rw-r--r--    1 root     root        159232 Nov 29 23:13 efi-eepro100.rom
-rw-r--r--    1 root     root        157696 Nov 29 23:13 efi-ne2k_pci.rom
-rw-r--r--    1 root     root        157696 Nov 29 23:13 efi-pcnet.rom
-rw-r--r--    1 root     root        160768 Nov 29 23:13 efi-rtl8139.rom
-rw-r--r--    1 root     root        160768 Nov 29 23:13 efi-virtio.rom
-rw-r--r--    1 root     root        156672 Nov 29 23:13 efi-vmxnet3.rom
drwxr-xr-x    2 root     root          4096 Dec 17 22:04 firmware
-rwxr-xr-x    1 root     root        206024 Nov 29 23:13 hppa-firmware64.img
drwxr-xr-x    2 root     root          4096 Dec 17 22:04 keymaps
-rw-r--r--    1 root     root          9216 Nov 29 23:13 kvmvapic.bin
-rw-r--r--    1 root     root          1024 Nov 29 23:13 linuxboot.bin
-rw-r--r--    1 root     root          1536 Nov 29 23:13 linuxboot_dma.bin
-rw-r--r--    1 root     root          1024 Nov 29 23:13 multiboot.bin
-rw-r--r--    1 root     root          1024 Nov 29 23:13 multiboot_dma.bin
-rw-r--r--    1 root     root           768 Nov 29 23:13 npcm7xx_bootrom.bin
-rw-r--r--    1 root     root        153728 Nov 29 23:13 palcode-clipper
-rw-r--r--    1 root     root          9882 Nov 29 23:13 petalogix-ml605.dtb
-rw-r--r--    1 root     root          8161 Nov 29 23:13 petalogix-s3adsp1800.dtb
-rw-r--r--    1 root     root          1536 Nov 29 23:13 pvh.bin
-rw-r--r--    1 root     root         67072 Nov 29 23:13 pxe-e1000.rom
-rw-r--r--    1 root     root         61440 Nov 29 23:13 pxe-eepro100.rom
-rw-r--r--    1 root     root         61440 Nov 29 23:13 pxe-ne2k_pci.rom
-rw-r--r--    1 root     root         61440 Nov 29 23:13 pxe-pcnet.rom
-rw-r--r--    1 root     root         61440 Nov 29 23:13 pxe-rtl8139.rom
-rw-r--r--    1 root     root         60416 Nov 29 23:13 pxe-virtio.rom
-rwxr-xr-x    1 root     root         65536 Nov 29 23:13 qboot.rom
-rw-r--r--    1 root     root        154542 Nov 29 23:13 qemu-nsis.bmp
-rw-r--r--    1 root     root         18752 Nov 29 23:13 qemu_vga.ndrv
-rw-r--r--    1 root     root       2527328 Nov 29 23:13 skiboot.lid
-rw-r--r--    1 root     root        995000 Nov 29 23:13 slof.bin
-rw-r--r--    1 root     root        508014 Nov 29 23:13 trace-events-all
-rw-r--r--    1 root     root        524288 Nov 29 23:13 u-boot-sam460-20100605.bin
-rw-r--r--    1 root     root        421720 Nov 29 23:13 u-boot.e500
-rw-r--r--    1 root     root         39424 Nov 29 23:13 vgabios-ati.bin
-rw-r--r--    1 root     root         28672 Nov 29 23:13 vgabios-bochs-display.bin
-rw-r--r--    1 root     root         38912 Nov 29 23:13 vgabios-cirrus.bin
-rw-r--r--    1 root     root         39424 Nov 29 23:13 vgabios-qxl.bin
-rw-r--r--    1 root     root         28672 Nov 29 23:13 vgabios-ramfb.bin
-rw-r--r--    1 root     root         39424 Nov 29 23:13 vgabios-stdvga.bin
-rw-r--r--    1 root     root         39424 Nov 29 23:13 vgabios-virtio.bin
-rw-r--r--    1 root     root         39424 Nov 29 23:13 vgabios-vmware.bin
-rw-r--r--    1 root     root         38912 Nov 29 23:13 vgabios.bin
-rw-r--r--    1 root     root         16384 Nov 29 23:13 vof-nvram.bin
-rwxr-xr-x    1 root     root          3456 Nov 29 23:13 vof.bin
$ ls -l /usr/share/OVMF
total 8192
-rw-r--r--    1 root     root       4194304 Dec  4 18:41 OVMF.fd
-rw-r--r--    1 root     root       3653632 Dec  4 18:41 OVMF_CODE.fd
-rw-r--r--    1 root     root        540672 Dec  4 18:41 OVMF_VARS.fd
$ ls -l /usr/share/ovmf
total 0
lrwxrwxrwx    1 root     root            15 Dec 17 22:04 bios.bin -> ../OVMF/OVMF.fd
```

**Comment by sujkosz** [comment]
I just found that you need to install qemu-system-i386 package

**Comment by NN708** [comment]
> I had the same issue and just found that you need to install qemu-system-i386 package

While this may serve as a workaround, I believe it's not the appropriate approach to use files from x86 emulator to run an x64 virtual machine.

**Comment by phrdina** [comment]
Thanks for the report. This is a packaging issue in Alpine Linux. They ship firmware descriptor files in qemu package regardless of what is actually installed. So if you check `/usr/share/qemu/firmware` directory you will see several JSON files.

The root of the issue here is that virt-manager tells libvirt to use firmware autoselection, for that libvirt looks into the firmware directory and tries to find first match. The file `60-edk2-i386.json` is matched before `60-edk2-x86_64.json` so it picks the i386 firmwares. However they may not be installed as they are installed by `qemu-system-i386` package.

Alpine linux should fix their packaging to install the firmware description JSON files together with the actual firmware binaries.

Libvirt should pick the same architectre as host for new VMs and libvirt should pick firmware only for that architecture so it is strange to me that it selected i386 over x86_64. Can you please share the XML of the created windows VM?

**Comment by NN708** [comment]
I checked the `/usr/share/qemu/firmware/60-edk2-x86_64.json` file:

```json
{
    "description": "UEFI firmware for x86_64",
    "interface-types": [
        "uefi"
    ],
    "mapping": {
        "device": "flash",
        "executable": {
            "filename": "/usr/share/qemu/edk2-x86_64-code.fd",
            "format": "raw"
        },
        "nvram-template": {
            "filename": "/usr/share/qemu/edk2-i386-vars.fd",
            "format": "raw"
        }
    },
    "targets": [
        {
            "architecture": "x86_64",
            "machines": [
                "pc-i440fx-*",
                "pc-q35-*"
            ]
        }
    ],
    "features": [
        "acpi-s3",
        "amd-sev",
        "verbose-dynamic"
    ],
    "tags": [

    ]
}
```

It appears that `/usr/share/qemu/edk2-i386-vars.fd` is referenced, but it is only included in the `qemu-system-i386` package. Since this is a packaging issue in Alpine Linux, we can close this issue and track it at [alpine/aports#16825](https://gitlab.alpinelinux.org/alpine/aports/-/issues/16825).

**Comment by sertonix** [comment]
I don't know much about qemu but is it intentional that there is no `edk2-x86_64-vars.fd`? It seems odd
